apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
stringData:
  admin-user: ENC[AES256_GCM,data:h9J+FV4=,iv:Z1nOt7gQ7J1sqD9Fw3dqbVBrXNxu11rasvmdteyeOtg=,tag:m5mEPTF3zQs6oDLi3VIzGQ==,type:str]
  admin-password: ENC[AES256_GCM,data:rKSz52xFxLlWJM3gP7o6hr57aAt3oYpFBRqruRuE5Ko=,iv:AAAkh1x1S1rw4PiT6Z4YO5DQm1cMyKqGqG9t37bM6vI=,tag:3/LCGxFfpBiDNTYtsm82AA==,type:str]
  INFLUXDB_TOKEN: ENC[AES256_GCM,data:QYReSXIQRgjOvAmL3rZCOjVCLql/KNjXhqaaabsDFJqZNsUATvRa/+j6ufg7Vol80TNrJNv5QcYMXiUmiY+9PQ==,iv:YMjuXK1eo3Reg3+xYzGFrddQE3RI7dIxQDv27tGWeag=,tag:iEHteDVTkPQ06dx9nzDuFA==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:5miOHmi2Qqc0yxcW44JNNjoSUgo6cW0OX0uroQgUwJc=,iv:fzALO3W/SgYfp2n3Rc+3B662LbkahcAZu160hqRLvCQ=,tag:Hy6G3g1UhPCcsvx0Q3q1EA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IERDNG5aY21s
        THQyVUpXMjF0L3UrR3NUWGxQTktUS1VuZjlmT24wSE9KZmRQZlFtb1dMY28xK3lZ
        elpXaFZ1ZUxRVENqNUt2cTZKTFh5TlIxdStaU1IxYXhWYlpVVTBQa0x6Q1hGMjFW
        RW1uNXR6WDAwQkdkYVlvTGkxc1M5aXpRaXBYTm5jdUwyNkw2M2JJVHNmUGx1ZnlE
        Q294VUpJSGNMbnpLVkNidkRXaytpL2V1cFpVdWE3a2dWN2oxSWNBaCs5UjlVejJz
        Wm5BR09ZbTZCcStFZHQ1MHV1WGFjY1hZaXlVUkFJZDRMc1p1MkJtSFRWU1NSUVJK
        SnJNZTlRY2RBNDlCWDRhU0JXS1VmbGNkNzc0dEJ4Sm9vbHhuUWJSZ2x1cnZjRlFy
        NElzeVNyck5QOWV4Z1hqZnQ5UE1vMXBIWnMyWWZTOFdFSVVmZzN6c0xlclhveDZE
        dlZzQkJrc1UrTlNCNS9sbWhRSTErRnRaVFBKQk1wNzFERUFieHBkbEhOTWJGU0lE
        b1hIaWxnYWZqWkFvYlRUZXhNTmd4WGh6emxzdVZVNTU1cUVneWo2Ym9Oai9NQjg3
        c2k3aXR3WW81VjFzV2JvQzU0c2wrTmxaL2p4R1lSa1YxNU5iR3k1SmIvV3hYbXln
        S1ZPZ0JRdURnbHMxMm5hMzlmeVFlVGwyWmFldVN3UjBQc21lRkoweTlVTFI2OFFk
        cWx3dDJ1ZEpHanRzWFpuNlo3R1Z5U1JmckM1b0U4dXczOTRLL3pBNjRjUEpGV3VW
        SFlSVEpkYzdiQkp0cDd3VGVJYjUrcFllUmNKOXdMVktPL1M2YWExUm5PYTN3S3BF
        UjBnNGhQWGx6elptYjE3ZXdRWFV5UDhrdXZXQ21Ba3BxYnJCVGpqdk52Tm9XU3FZ
        TjFGTVpEVlFxVnZCZHJ6OFozank0Z3Zxak5TWk1aQm1zTUYrV25HbTRKbVFPMk1t
        ZHZrQkF6QTU3U2liT3NSWVBEN3ZYOUg4d0s0Z2V0UFdHSy9saDJkT2hpVlNWOEZU
        ZlIvZk1IOVNDR2YyNW5KWDg3TnRxTjZEM0FzYys3UWdEWHNzaU0yQmdoRmNPaTZ1
        MHV3WXNwYTNMbk1jVzlDQ1QveGZyaHhxc0pSUUxxRXI4UCtYVkwyRW5tdjlpSHly
        eTJaUVZ3Q2pra2RFUExXaGtVbEtHeUZwR2dSaUxVenJIKzlMbXBiZ0N4N2h4WUt2
        bXRBaDVhK08zaHlZMzB4b1BXczZPYkgzemZDdTU3UkFYR1BXS0ZaUEp2b1NiUXV2
        OFQ5a1FGWGZseUtNSVRoMHJpNUE0amFzK096STFjalBzbnd6L3VkaXdUMENzb3ha
        dmd6RGRqZWJma0tQK1lBdlZUZExacWUyenZTb3RNMXBRV3hhUEU5djRJK3QxT1FY
        SEdNcW05OUtRNEprZ3lhSk1EQlZuQ1pTUW9WY0FjYmo1blNUREVVZFYyeXFlaGpR
        dVIwR21kU3M0UXpqbUl1ZWxkWDk2Zm1NZFE3K2xVbnlaRWNMQmRhR2JsQzl4dnE0
        aGVXUS9ELy9Bdm5ib0hmWGJSMCtwOVlPNWVMMXFESXVKeU04R3NPRzVGMmZVNUJD
        UEwxMmlkbG81eUtoK0FrMlNiQjNXMUZ6a0gwdlIvUjVGbFBma2FtN0g2QlpQekdl
        eS95L3h4TjR3Q3p4UlcvcitZQ1k5cVFTLzFicjhmRTlySGNEU3ZxU0J6OU8yb212
        U3pKUjBKcHNIZitQWFRrOTJtekFRbStlNHc2Zi9qTnZpbk9XWDkzd25HWFpUdlJY
        Qk1YaGZpYmNzME1ORmFmcmxteGF4R1djeFNKaTFlaUxtK25heFlnakI4TXNnM0Z5
        aDg3c2ZwbUsxTVU2RFprNS9XYllLZE12bnRKN2JSWGtkaVZkSXYxTU9vaXhGZW1Q
        OHhNR084UVZjdGJyMUxhRDN1R2NranNrNmF1VldmUDFrbmxTTmtYenVtcWJOZwpi
        WXRyeVJTR2w1STg4aG5sTmJDa0NBQnB6cG9ERW9BS3NWcGpPSUZJKzA0Ci0tLSBV
        LzBCRldZUHhJbE4zZkRPWE1JK2ptUGRVRWpwV2I2RkNOcEN0Y0JXcytFCh17CBHf
        x0SyjkCneRBIEm7mEctXhvvancEh1sieUZJzvfZJg0ZPJh8pK3YBUSmUIWAyTFQq
        h9rEwXLdECTPtJ4=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1zev40t6r439fzn9dddxrz5zq9vzzmq385rv59s9svf7qred0fqcsp4y2pn4rhpgjjgez862xf4rqyy2ytldkrw2g29fpesmmq7agzterhldmgsz3zjjwla5c7lq2hmac8d33vdg7js53zcrk8wtfzewq50ugrfzw3x0ghlrl0pmuhy3y8xhytgtyhfwqpup2gurfnkd8c2rq4q2w5zcvqg5h9ydcdlv4jhhkgwf2d39njwgc497vfd82fat4c50yedx2ajedtpeyrlqnf0fze8p0za3hypkzaqfnrhfx8zgrfp7qx3gzez6tf5vcpxyrzlup5evf0tqhtz30t4ckt9njc4vrw2mgtvxkl9upn9y34g2r36g4vvdy6mzse2vk5k26gym5cfr4ef65wvkhcv7yqag6mpfkqmxtzxe8yedhsnq2x9vuxqyx47rkvn5g0w6nf8yqs8t2gp5cp0kdxruesp0wh76n5wmm0ztx4pktwrharstredmlqeec22045wm3f9hhkz6fr4y94vzugr9ghaqhswrh7dx6yc9mc0y6u6drgtxesf0jsh89xg3u47yjvd3rnkdu22ls5j0hpcwymlr6gp8pt9qyc6swsczj50rq9rppsl6ufxv2kwcrmvtvn2svj56ryukk006l3wwe9plx6wz24y3xq0jje7rxkc86w59d0y6q2wf49whuzt28xf3zvmp25qwzxn4ms24pkw7g5w6xq5nnwyvanl72kqcztlssyjs9hzdrq2m268mktc8jhydnvezteghq40r0k772szggkhv8k8gvf0rn7346h0cv852cksx53tqdgqsfmjfsv6m6gcdhc4t059hx2gh4ckryzptper3hg3265usmnyclfjdxxr445602vr38xlywucmmxlrjf36nrn060jrtvqrfayc7tt96skkt754fqgj8zwd95cht9wz3x4ptsruceym727xv3fzqz56vt2my6slx2dwdpg962mpuxgdh3mz8wq5y3ymgcwakx9tjcge4ah6883qmhyevkvgay08t54x25yqkdtt2naspeyp97w04jjcv2kcgdzutzy5s23855aahl2q9rvwgc5cke56fg08x9v8mvydmgc48248hxx96ewjlhscl633afyaceeynk4tk2hvsuxd546ukp23s7crsj7rne2rqrxwkvkpld87z86wpcus2xf2h6cjr3xvcfrxqnphm08r3gxyn8g9v4sjztdv3p4qvfdk55sv66lryh5dmtxu99hwuexhpfyfz5496rawwc3rvtep4ylzgvaekhs4eadfzy6vckwpp37hd8q6xyvm2vcja69ppdzj62k22pg8u64l024skq3ejcgr3cqnfv5e5dzryxyr9qtc23t8pn0mhegj9caa89qnd6ck9xpsnfwlckz8xxykqf4egucryapssecetxt4e4q599g4a0y4ccswpykhsrd5wjvt32gtena5kg38yd04d4y3zhdjjlnp3tqwzux090268x3pvgqfyelr04ftnrjrk3hm9hrsg6gzex8qul3fu3uq8wg4aqr8vgeff5as5lcdq6zlkc3p9jpcdgar82wxxwgzevfju9uf8v2kqgjpfy5tsldv9udjsdaj2tf4uuknp0f6yksfznd8mtrmle0kjqa9qjeg7k8u8nll3k3qc0s0c9qxj7atp4janes0ud9ke9jljy3grf2th0my3eqcn4aumntx5276g3ccvy6ueujcvy8npz26x277tc995756rptur0jjwx06qeqpdcdguugnk083js8xf2q7gcsmtympfjvg8xrempvj29qrsaym3dqlkv3gjayelfnpl02acd3nsqv69jqg8ewkjp3spwnvc7ql05ke37utdttcgq0fhc8a4npxj2jhhdhazu494z4n772qq8wazqcc7qqvq0axs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-04T17:22:17Z"
  mac: ENC[AES256_GCM,data:neJsR6jQfByGrhn6PzxWke0VhwyfqRepffVqkpRUElWi5L8y5HXXBoCdONQUV3zDpZ17T/desWGh9YmQoRV89YjURYAIrmYhXEN2U8goOJvecBnMaizukt+mazLj/hulGeln/jWCNM37KdHH8SrRiVv2NfXrpEUDRn/JVNX+wKA=,iv:0GwfCbLAyqK1cOvJ4nwHRrxdYSNlhC5tJpAPY2PY1h4=,tag:pDQb7Uohv59n501i6F6daw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
