# The server reads redis.conf, so the password is never in its arguments.
apiVersion: v1
kind: Secret
metadata:
  name: redis-auth
stringData:
  password: ENC[AES256_GCM,data:wiSA+i7tBVR8q/Wjb8yEoM4fqKFu4vAya6ikBuLKY9LLAp9sDbgXHF+ZB9lnky2fK/1ZH8LuPmAolSkk+mZS5w==,iv:ni30qcO9MW7OVUKblarDgThq+KPX6HV08asWRpErnVU=,tag:uRaPUa6t37IawyLeYv7LEw==,type:str]
  redis.conf: ENC[AES256_GCM,data:Ek6dTJ3/YaOVWOwaVr5zrCBZEK8mp2vt25nAMaArLah8iu4clFITRiQUG0uqzIHqz/gQI6RXN6RkEVQeFLRqYiBxPpGvoyJLGwseew==,iv:lKBvoWFcc5Ux2GNArOT2LgzU1ZPKn1hg8QvXPzJ+1UY=,tag:6IjqDkiDtaxpg3tL+G1S5A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFNwb0N0U09S
        UzhQNnNVTkZtVzMxMnR2RlQxRzl4a0FlZWswN0xaalp5NStOblJudi9GMDNyRC9W
        Y280dFd1TmxoRXpoM0U2VUdXNG9IbXRTVVNGYUpJSlVDOXV5SXhRTS9LaG5vbk43
        QlpyL2NNLzFwVnJPTjNNaGRvMFd6azZkT2IwZkxWQ0hlMUtGUjZBNHBmbUIzbG9X
        ekM4djVabmNuU1FTVE84ZkYzbXMvb2NtOS83VzJYOGpVWTRZcjdrdkYwRlhOODlK
        dWZRY0VxOG05MjVYNWhmbjF6eDh0bXQrZ0VGN3RiOEsyU3Avd3dKbzJUd280S3Fk
        NzRScXhuWWxlQXhuendTUFA4RC93b3F3VEtPaGZjaFRwQ2NmS0RsaThsa0Fab2Vz
        enM5Zmk4UUxaeVdqQ2tPY0ZQbTgxbTlMZFpOSnN6Ykg4b2ZtK2tjY3hWSjZEZjlQ
        OFYrSE9NWktLQ2hnbDhXNXFRRk1yLzc3UkdGMnhpRkxqRjI4QTUvU1ZuS2htc2kv
        bGxUaXJqMkFiNmFwakRGNFZ0SjU4NkRZUGJwKzFDdk5iL25RTk02NGRod2FSTDNw
        RDFLTEJiOHdCUVNubUh3YzZxRkY0TWU4bEExZmtTd0llN0J4Z0w5N3hua3ZoT1h3
        bDVJNFoyV0dhOGJ5TGYydDhiOG4yTU5uVVduQTJaU0Y5VmQ5TUtHODU3SlcyWHlY
        V2hhRlZXODRaNHltK1ZrdlMwc0x6amhGYWgrNmxnNGJBSnVKbW9vdUpSQlUvVmpq
        SXZuTXlYZmdiQ2cvZ0JMajMvREpMcE5Qdi9FMmdJR1h4bEp4WGIzVDZ6S3VibDlh
        akd0UmRqTVNTWWprNmluVHJFOEtialkwdDJtVVozUThyeEkxdXRnMTA3a1NqdjJT
        MkRkYm9tNC9BMGpSeEVoZVI5UzhIZXprUjhtdkdEY0N2YUREWWRWOHZRMXhHTFky
        RitpQTV2QklvVkpuVmJZK2l0U2xLNktvZWRRZXN4Q3E5QmpxeXFwYWVKMWJubHE0
        TnAxcVE5MGRaelMvZHBTT28rY3lpVUUrQ0dNaC84b3FkOC9nU2JaKzN0YVBmQ3lF
        QVMwN0VmT2FXdGN0bFI1bVdsalJKRVA0dkMxQXRuZ3psSkIzVVZSVmkyK3FGTUxu
        VnBFanJqcUlyckdQTkxKUm5YT2Zhd0hidER6TTFyMVVUYTFZZEFLYmVOajFRdmZ0
        bXhyUC9MWkt4UkFoREF3akMwVURNcEQ1T0Q0MFB4SU5vMmN2QzN5d0k3Tzg0cFhM
        RU16SUd0U1NISFd3MVZkVS9xR3VxYXllRGIyZUFWQS8ybUc1eWFUb01xaHpLY2dK
        N3dZZjhkSWh4MEhyVTN4WG9ZVjRteTRmNXdvNEtWczdyRUFRdWZMSW1CdGtFWWhs
        Z0ZZUzgyMUkyNHpqWDE0NEdsSVhlUVFsV2EvK0orNTVXa1ozanFSUm5UcDhoVW8y
        THNJVGw5TGFoMnpUOGhPUjQ3WnFwMmRQQ2ptNlN4NEpRYmZTajV5VTNDSXJOR282
        MHA3NzVJd3BoMVRxL1ZhbGMyd2lreWxha2ZOZVlXaHQrYnBiQmlGRjRCTEh6M204
        YmRKNTdhN0ROMjkzamlRZ2UyTElsdFloMzh5MXVHS2p0RWxvU0xhMnZqQXdsRnFD
        eUNncE9vNHFpRjVoWURjNmk3dmw1aGVwVWcrQzBpRFFBbXZrc21HKzJBanNqeVp0
        Umg1K3duSE8zc1NUK1c2MzgxYmFNR1U4OXVFRkVtWjJFbW1paUROcDZsZmtjVmJB
        bk5zNkkraTVHeU9WL01VdVRNSnZRbm5BSDNoZWVaUE81ZC9WOE1OZGM3MUYrUzZK
        ZlI0a1VxTUl1eUw3K1lNbkZCelJibnlxYk9hMlJnWGRVMUFtRm9WdThKUTJSb014
        STV0RFRRQmQvMnRla1o1c3UwQlpPMVVIUUdiY3kwTm5nOWpLS2xkd1FJVG9hUQpH
        cndIdFhrVktRb0pqM1MwcFk5MFBrakVxeks2ckZjMmUxYk4xc2pZbngwCi0tLSBV
        QTE4NmFpUENrbWZEdGNNbVZjWDR4TTlCYU4xUENLS0V4TW10dXh3WWFBCiAUDkzL
        Fu104fyV+iy/SZSqiSc48qG0NxQP0aP51XoAY+oOzc04zw4Y4Cxi9gkfyITS812C
        /5u3XTnICOWjHms=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1zev40t6r439fzn9dddxrz5zq9vzzmq385rv59s9svf7qred0fqcsp4y2pn4rhpgjjgez862xf4rqyy2ytldkrw2g29fpesmmq7agzterhldmgsz3zjjwla5c7lq2hmac8d33vdg7js53zcrk8wtfzewq50ugrfzw3x0ghlrl0pmuhy3y8xhytgtyhfwqpup2gurfnkd8c2rq4q2w5zcvqg5h9ydcdlv4jhhkgwf2d39njwgc497vfd82fat4c50yedx2ajedtpeyrlqnf0fze8p0za3hypkzaqfnrhfx8zgrfp7qx3gzez6tf5vcpxyrzlup5evf0tqhtz30t4ckt9njc4vrw2mgtvxkl9upn9y34g2r36g4vvdy6mzse2vk5k26gym5cfr4ef65wvkhcv7yqag6mpfkqmxtzxe8yedhsnq2x9vuxqyx47rkvn5g0w6nf8yqs8t2gp5cp0kdxruesp0wh76n5wmm0ztx4pktwrharstredmlqeec22045wm3f9hhkz6fr4y94vzugr9ghaqhswrh7dx6yc9mc0y6u6drgtxesf0jsh89xg3u47yjvd3rnkdu22ls5j0hpcwymlr6gp8pt9qyc6swsczj50rq9rppsl6ufxv2kwcrmvtvn2svj56ryukk006l3wwe9plx6wz24y3xq0jje7rxkc86w59d0y6q2wf49whuzt28xf3zvmp25qwzxn4ms24pkw7g5w6xq5nnwyvanl72kqcztlssyjs9hzdrq2m268mktc8jhydnvezteghq40r0k772szggkhv8k8gvf0rn7346h0cv852cksx53tqdgqsfmjfsv6m6gcdhc4t059hx2gh4ckryzptper3hg3265usmnyclfjdxxr445602vr38xlywucmmxlrjf36nrn060jrtvqrfayc7tt96skkt754fqgj8zwd95cht9wz3x4ptsruceym727xv3fzqz56vt2my6slx2dwdpg962mpuxgdh3mz8wq5y3ymgcwakx9tjcge4ah6883qmhyevkvgay08t54x25yqkdtt2naspeyp97w04jjcv2kcgdzutzy5s23855aahl2q9rvwgc5cke56fg08x9v8mvydmgc48248hxx96ewjlhscl633afyaceeynk4tk2hvsuxd546ukp23s7crsj7rne2rqrxwkvkpld87z86wpcus2xf2h6cjr3xvcfrxqnphm08r3gxyn8g9v4sjztdv3p4qvfdk55sv66lryh5dmtxu99hwuexhpfyfz5496rawwc3rvtep4ylzgvaekhs4eadfzy6vckwpp37hd8q6xyvm2vcja69ppdzj62k22pg8u64l024skq3ejcgr3cqnfv5e5dzryxyr9qtc23t8pn0mhegj9caa89qnd6ck9xpsnfwlckz8xxykqf4egucryapssecetxt4e4q599g4a0y4ccswpykhsrd5wjvt32gtena5kg38yd04d4y3zhdjjlnp3tqwzux090268x3pvgqfyelr04ftnrjrk3hm9hrsg6gzex8qul3fu3uq8wg4aqr8vgeff5as5lcdq6zlkc3p9jpcdgar82wxxwgzevfju9uf8v2kqgjpfy5tsldv9udjsdaj2tf4uuknp0f6yksfznd8mtrmle0kjqa9qjeg7k8u8nll3k3qc0s0c9qxj7atp4janes0ud9ke9jljy3grf2th0my3eqcn4aumntx5276g3ccvy6ueujcvy8npz26x277tc995756rptur0jjwx06qeqpdcdguugnk083js8xf2q7gcsmtympfjvg8xrempvj29qrsaym3dqlkv3gjayelfnpl02acd3nsqv69jqg8ewkjp3spwnvc7ql05ke37utdttcgq0fhc8a4npxj2jhhdhazu494z4n772qq8wazqcc7qqvq0axs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-05T04:13:19Z"
  mac: ENC[AES256_GCM,data:fpzK3mSsFkum8Wym/fzjTfkFhTnt81S4wNwZftjOnkkCG1iX/AQYNSia6ghSMLZzrrxaPEco7e5SfIkbCCmyxRf/bO20Sj9m1Wd+8osChID+JVXqVXiZZZ4y/CEvFadf60bxcb1HotIzz7pcwxDXPMFK7tp99ppPeloGQR93IjY=,iv:KAZbuXOc+AI5uYFcvDIcvaDwY87RQLB5OVLLUVY69Nc=,tag:QzW/lEaZ4lnRESODvNigew==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
