---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../components/postgres
  - ../../../../components/redis
resources:
  - ./cluster.yaml
  - ./helmrelease.yaml
  - ./helmrepository.yaml
  - ./httproute.yaml
  - ./networkpolicy.yaml
  - ./scheduledbackup.yaml
  - ./secret.sops.yaml
