# The account ID is here because it identifies the Cloudflare account.
apiVersion: v1
kind: Secret
metadata:
  name: sure-secret
stringData:
  SECRET_KEY_BASE: ENC[AES256_GCM,data:FLtwUGuoFahshWkEF9iQMkUVfcwqUNGQp4TqdNCxqTFT1RQ/TNPSgndtKTkEyR3blb7SNcCIjZ/RqiqANNnTG1lyqe8cY4YW/B3LdgoY6h2XvU673j/ucG9ivritn3C2ABHckvxKxHdZQnKWn3PFzgET2bm/Xy9/iYxPfIS4JbE=,iv:YUZUw9pcjFI9ab3blNU/uYYWewMGWiYZK4r3gyg7QMs=,tag:zbHchzuvDNWQusN3jMHgrw==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:JX5ffp2bx8uT4mD/t2/bPjnsctb8ZfHxyOfvxx8xnVE=,iv:YTG2OTR0vE8xo8cJyhHO1tQgYpbFD41xSDzXZ5hY8jU=,tag:jnCwjW+MbR8lQOoUoHre1A==,type:str]
  CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:jCYeCvNwCb3E5N2Vf/BtGNpn1Ze2bz0TmhYbk4B0WcU=,iv:1CEH30CGGjW9d3okDe2GLc8bF15XqrHUfl8A8sxak68=,tag:i4Y/sfpTUu3LGOtOdZOB1Q==,type:str]
  CLOUDFLARE_ACCESS_KEY_ID: ENC[AES256_GCM,data:qidPxzbVeexbU3x1w5i5r/PZcw8Y22u13HcHXTG7TuU=,iv:ioSA4QfeU2IwSTNTnpoQM30p0EESq+Q1OaybmtXqrMw=,tag:v4kROhGeW3KMQPTKNdoCFA==,type:str]
  CLOUDFLARE_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:nS869krTL06f73tGeMc0YcI8j1aJ8MVWxjrXu6sJMGrtrdDa1PAF2JcvgTuCdU3CpKcMeF0DEgL8HqRWK0k1cQ==,iv:0tayYPXoLjegxQGIZd9L8PdSNC5YQ4va4fCIyHhi+CA=,tag:PZMBk1kYQC7Vj0zTeiy4Jw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IC9UY2dqNExy
        YVd4L0w3NG4rN2FDTWtiS2ZrSmRKeUg1Ukc3Y1gvd2hiTVM3c3dmZHZhMHBTdEFo
        M0NFYWVwQXlhY0gxRkxzQjBzSC9DWFFkQkdzZnRDaXY4c2dGZ0xhOFd4djBBUWEz
        WkZ6MHMwVHBiNFRpT2pqT25sY0FtQ2JycHNNbHRNQ29kQ253R053cUtsd1BuN29j
        cm1MNGR0TmM0MjBOSEpNN0RlcFl1U2RaMzhSZUlmVjk5TDR3cmU3b3FUQmxoS2c0
        MHduL1BJeW83Qkh1d2dzdzBlNlR5NUpQRkp5SU5uaitqeElIV2NyVDBkQm5pRTk3
        dTdEaG90d0pqbHgvQWkyVFhCK2o2b2xZcWZ4cFovdm1lRGZuWTNYSDFXb1VyVmVR
        Tkp3bWZWUVViT1gzWElJMndPN3ljQjAyMnpOdHliVVFiYXJldWJWNGZOUDRXSmk3
        UmZIaFJML1ZJUnI1TWlxdGRueWRpOUZGd2NRQ0k1NVEvVXg3b3ZJRlpWaEdPbE9j
        RWRZcUh3NDNKWVNmejUwc3N4OGhXYXNvTlZaaTYrbERha2s2bnB2YjFhaUlQOHFq
        YWRXTmJtMlVRcll2OVR5bFlBUUNLb29XSWc4WWlOdVhSZTB5SXJoamhEZ3VBcnpt
        cHJ5Wld0eVkzdVRKb0d2c2ZRdnQ2Zkp1eUVtb2Jid3N1N09DbmpwM1NLdUFrZ2pX
        S0o4SkFXTDM0MnhKandZYU5TR2FkMjMzbHdOTnB6QklEcEtPdUwxWVdzMEJMNVpL
        eHRUbUFVTE1MMkFmZTVReG5rZFRuT2ZmbG1QeDZUa1hGRkdJVFU3b1ZEd2NNczNW
        S3ZMMHNvYjVtKzRId0RzN01TSDZUa3VqcDd6VlRSL3BFditIZG40enQrdWhpZmt3
        SWxNYnZ1VFFtVDhvd0E4c2c1a0lEelRvTWNlKzFteGJhek5yMXJyVEtJeGcvTE9q
        Z1ZoT29kbnpuTytMSkk3bXBKMHRraisrbldGNXUzK0xGQjVxejZ0cnB5K2pFQzd4
        Z0xHRTFNSWFMWE10blp4MnhDQ0htRXl0bkVZNEwvWm1sNHJoUUE0blVvb05VRmJC
        RUJVTlRWV0d4cHBkMkExM1NSSzRqckR1eDlHSzk4T2xLTUZxYkVlSDFMU3JHakcr
        NGpKMDM4N2djRk5CRkYrb0tsN0dTanJCUU5rUDFpR2FWVkhuS2RPZ3V0dWpxVVF6
        T2NGSUwwbDB0VFhnb2w0K1FwQlNXR25aNE1NbHZzbWQwNGlaTDZZVHV4Y1dqdVZa
        SjVNOFVsS05wd1Njb2xyVnpkVXlNQjRwMmNlLzdqbkxUakJtdGR5bFFXY0p2S2lp
        L0NDczJPdzhWMHhqeUFnbmtJelZ4a1huVHdORGt6T25UaHR6bG5GVVlKVVg5Q0VT
        OFFtSklMbFJjSzJwVzFXVndDRml0ZnRVelY1bGQwQkErbzBKc203NDJsWTJld0c2
        WWVSd2ZRU1dGcS94UnZTb0FTdXdrUDFzOVl6U2N0UWNGNG0wL0lLNXN5MDVPRzhL
        ZDZ0aDhOZSszdUVua1ZQUFBYMVoxTUZycmczbWpMVHFxeTY5YVZTNnRaV1kwK2pq
        UkV6YjNZTXV2cUFjVGFMRjdMSldEaEJqZzhNV3ZtOWJReHBtS2lCeWt5OEhIMzQx
        N1A4eTZ6aHNOd0FsQWwvbnl4S3hoT25kRzNzRHh3RWVHV2YxbFlhSnpEdWs4aG00
        WlVkVkV6RHNucmtTQS9seWd0djFlaVRtZlRpZXFUWVlFMXNob1J4U2NWdkgwM290
        ajlIbVlqeEVnb2xsZklyWUY4K1hHVyt5c1VkbnNzZW9lWS90b0hZbW5scXY0cFNF
        K0x2OEoyYm9ndjJEUGVyYTBOWVNSQldTbjZHa1N4SDRxajZKei9kaGJhOGMyZWpZ
        QlUrazErUUk5S2cvNE1qRlVOTnVBTUFHY3E5RVFzZWhLZGIxVXRpWEdOb1FOZwpi
        ZUFLRE9ScGJqQzdSTktnVCswV1VrWVF2a1Q3TVhqSUx5VG9ITXY3QTMwCi0tLSBw
        Q3cyeWs0QlFqcGl1MVVoU2lBUThENCtucjRUeUh0dE94RGRWUWRhRmE0CsNQHYkw
        4pdwcohpl9IVvy8Lg1pODixZKMVDQfROFgrBgu9m3aTUmcby3ttozQxTvIv3MHT0
        ctqVwM0Rp0uqhT0=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1zev40t6r439fzn9dddxrz5zq9vzzmq385rv59s9svf7qred0fqcsp4y2pn4rhpgjjgez862xf4rqyy2ytldkrw2g29fpesmmq7agzterhldmgsz3zjjwla5c7lq2hmac8d33vdg7js53zcrk8wtfzewq50ugrfzw3x0ghlrl0pmuhy3y8xhytgtyhfwqpup2gurfnkd8c2rq4q2w5zcvqg5h9ydcdlv4jhhkgwf2d39njwgc497vfd82fat4c50yedx2ajedtpeyrlqnf0fze8p0za3hypkzaqfnrhfx8zgrfp7qx3gzez6tf5vcpxyrzlup5evf0tqhtz30t4ckt9njc4vrw2mgtvxkl9upn9y34g2r36g4vvdy6mzse2vk5k26gym5cfr4ef65wvkhcv7yqag6mpfkqmxtzxe8yedhsnq2x9vuxqyx47rkvn5g0w6nf8yqs8t2gp5cp0kdxruesp0wh76n5wmm0ztx4pktwrharstredmlqeec22045wm3f9hhkz6fr4y94vzugr9ghaqhswrh7dx6yc9mc0y6u6drgtxesf0jsh89xg3u47yjvd3rnkdu22ls5j0hpcwymlr6gp8pt9qyc6swsczj50rq9rppsl6ufxv2kwcrmvtvn2svj56ryukk006l3wwe9plx6wz24y3xq0jje7rxkc86w59d0y6q2wf49whuzt28xf3zvmp25qwzxn4ms24pkw7g5w6xq5nnwyvanl72kqcztlssyjs9hzdrq2m268mktc8jhydnvezteghq40r0k772szggkhv8k8gvf0rn7346h0cv852cksx53tqdgqsfmjfsv6m6gcdhc4t059hx2gh4ckryzptper3hg3265usmnyclfjdxxr445602vr38xlywucmmxlrjf36nrn060jrtvqrfayc7tt96skkt754fqgj8zwd95cht9wz3x4ptsruceym727xv3fzqz56vt2my6slx2dwdpg962mpuxgdh3mz8wq5y3ymgcwakx9tjcge4ah6883qmhyevkvgay08t54x25yqkdtt2naspeyp97w04jjcv2kcgdzutzy5s23855aahl2q9rvwgc5cke56fg08x9v8mvydmgc48248hxx96ewjlhscl633afyaceeynk4tk2hvsuxd546ukp23s7crsj7rne2rqrxwkvkpld87z86wpcus2xf2h6cjr3xvcfrxqnphm08r3gxyn8g9v4sjztdv3p4qvfdk55sv66lryh5dmtxu99hwuexhpfyfz5496rawwc3rvtep4ylzgvaekhs4eadfzy6vckwpp37hd8q6xyvm2vcja69ppdzj62k22pg8u64l024skq3ejcgr3cqnfv5e5dzryxyr9qtc23t8pn0mhegj9caa89qnd6ck9xpsnfwlckz8xxykqf4egucryapssecetxt4e4q599g4a0y4ccswpykhsrd5wjvt32gtena5kg38yd04d4y3zhdjjlnp3tqwzux090268x3pvgqfyelr04ftnrjrk3hm9hrsg6gzex8qul3fu3uq8wg4aqr8vgeff5as5lcdq6zlkc3p9jpcdgar82wxxwgzevfju9uf8v2kqgjpfy5tsldv9udjsdaj2tf4uuknp0f6yksfznd8mtrmle0kjqa9qjeg7k8u8nll3k3qc0s0c9qxj7atp4janes0ud9ke9jljy3grf2th0my3eqcn4aumntx5276g3ccvy6ueujcvy8npz26x277tc995756rptur0jjwx06qeqpdcdguugnk083js8xf2q7gcsmtympfjvg8xrempvj29qrsaym3dqlkv3gjayelfnpl02acd3nsqv69jqg8ewkjp3spwnvc7ql05ke37utdttcgq0fhc8a4npxj2jhhdhazu494z4n772qq8wazqcc7qqvq0axs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-07T03:14:38Z"
  mac: ENC[AES256_GCM,data:JDW372JViOh15TqtDBlqjBMrN5IULpYBjnnfLZtWbbffHB2kaL5OnkiktkFSzysOR22eBFYJULbGXElg3B7d1btmiIu2ReTa5w8kk0qjroRBA3yaTLR+S23Zv4bVl5xAtbQHTM5uduNM83u9v89yekqpR4eqsS4FsLTivTBFtbk=,iv:uvVXUCkrp74/c9L4gaEFpH45GTm5bB/XR5+DwPOA3W0=,tag:n/53nH3wv6doZMp9ZSQqFQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
