# The account ID is here because it identifies the Cloudflare account.
apiVersion: v1
kind: Secret
metadata:
  name: sure-secret
stringData:
  SECRET_KEY_BASE: ENC[AES256_GCM,data:/BgyHFJ511SSc1oalF2Y4one8zz92E9YlPtlSLijxhFxkhvgG+3WwL+4kVMJAu64/5eRT84PQBBaGExcxL+ZHWaWD3w/YYCJw/HhGrbKcL5wmTJ/Oc6+3wkzANHA0IY1js0qO1E8uGfIvrB0ka3J2YqaLvgufSAzUjpPMhLsQVM=,iv:Kah6i9d9eSxbH4a91ifZKXk1Wod+O+DeNV05IFz4uPI=,tag:GpFXbMkbFd39k8P1yab2Yw==,type:str]
  ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY: ENC[AES256_GCM,data:vPbrhxisel+kU8ase1myPfodiWODt0MeaC4isigR5kIGnhFy1CfZ3q0qvdjhqt0069XT7h3zfvvnljKYj10aPg==,iv:+vyyteVu+ZYKTGwbQ9SrKflTvgdgaeTN7z1f7ozlC8c=,tag:3wYw6+ytGc01YvCJ48qApQ==,type:str]
  ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY: ENC[AES256_GCM,data:hkdiYAHBEhVKJbwbWXEF0sV+TO62J8vfo+t/0YLpX42g1tkgO32Gd/zwuzv82PMdAZQWTMBxDXlSx1iyuAdOow==,iv:SLi2awmv4ZqGs26nHvb0FBGqc6ccB6YsgLA77H5Ief4=,tag:wtNBXI8+LxXi8g+0F/sZuA==,type:str]
  ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT: ENC[AES256_GCM,data:Um2odL3/IP564YTZKr1N29tSL9pGbN7opEQdUZQ+9WyRpHY+TaWqDDlIcWkXahO3EootyMujM7QboGvBQkqlj1DASoDDbB4N2Um3LCpWiqZ85l29of+OJTuKtltbrnJ9ywnAT3yfW//Z4T+TDW1NL6/wP49Z2/toFXJJqM0GKfc=,iv:hwb2aaakfYml+uYIsFR1i8N7Q8X+PxWfsq66PXam4ZY=,tag:uECUF5CFvz75h+cUW6Ii9Q==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:8+6sp9trAKr8gpczUaSIf+dyPFqpRVT3j1SvhxH02Vg=,iv:99IpAiQ9GUy4m9IsOBM8b57R2ikcmYxf/PKwVa65Fbk=,tag:1oZeUrLhj2v0B8pLzEjEUw==,type:str]
  CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:U0bebRJCE1JNPCcIhO7RKJmnNK9CpsV31rjg2qlzi6E=,iv:zolHQLon18ziGr0aVKlcalJnvKM4zhyiPPJL+0XCXEI=,tag:McFOdxuBYOPecGGa+EZqRA==,type:str]
  CLOUDFLARE_ACCESS_KEY_ID: ENC[AES256_GCM,data:dmEGhlHphwxje9BD3xWv/UJ6TIH+ZLPH6lIt94mm+vg=,iv:GBB/0ydBCUb6rPKlOQdFErQmd0zgbsogSHNv/UwpKNc=,tag:YOkefUUYzg1V7Lf4yCUaDw==,type:str]
  CLOUDFLARE_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:aYQcKiiAJTINXy8NECx2FnpCHfOPoDorFkrMXTBHtaP+892HNsX5/2ZZ1KoJFczuFGnIEtHbmkCWWKPT9XxMnw==,iv:lTknQAB21i2xoXA8YwLOlS9bNulimC4tkGuf6tpVawQ=,tag:ZB4xSF8lpJo4Lto9mVlo+w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHhsTHFuUGRR
        dkJxQXpSQ3NuOVFJb2Z4SGJZVmRYRVZjSndMUEJJa1QzeGxPS1FCMXBTTUduOGUy
        U2NWV1dEWS9kc2FKL3hpMmw3OC9lb0p2dzFLcHBLdzdLZ0VrTnBVVEgvRytxeEg0
        Y3dQNmRwa2dLUnJET1RUa1BuUzlqWHROQXpSWVFqeEczdSt1bVB4S1ZXbzRybSs0
        NlBPM0lkL1QwcVcxZDZ0Z2dybndEVmNnd20wdWV5bnRVOU9scWVlSlNDWFdWRzhN
        SThEOFI2Rmc2emtVaUtjVFlzQkpIWU9SM244T3c3ZUZKOFRxdytFWURSYXpqWFRL
        bzR2a2hSdzkybWdEcHA2dEcyWGZ1S0syRldNYlZRVzNsT3Q4dERKVHMrNE55S29D
        T3BTOVEzQUN5M2RHeCtXN21ESlM2UHl6cUxyQU95SVUwbG5EKzNZV050bllWb0Nw
        Rkk1bGdBZFlDcXFtQVJWdE14VkVva2VhZUQrbkRiYk8zTnpMYjAwSlIzT1ovV0dK
        MjR3TitPS0lHc25ONk80WHB1NitoRjlaOHVwOEhOcmtDbS90czhqWk5yTStHeng2
        L3VWeWZlTXg3TjVLTWVKYWd0UVo5ak0zdkhSY09XOHl4RHVKTGJmWG1OUFR2d0Q5
        dWMvQlJwRFNnSWtEdFhqcWh0cEtYeDlNanZXSDlMeGZpZ3VScXc4YjYvOFBkSWtK
        dG8xeXVLZmE1TlRkVHpDektWUzZUYm0vS3hhZDF3RVlQV3grVkZoTnN0QjBxaVpZ
        RUZ6STQvSHZjR3FaVHZUSE03dWR6N1VTNkpNTGJ6b1I0YWJhbXFmM1pPRld4dW9D
        KzQ0NEtpakFzR3N6RXkvQlZhVEc0c2pIbVc1REtoOUxMaXhRaHJMNGlvVDhYVjd6
        RlFYQ0RqUkRjeHNmWmMrd2VTK0UzVE1pKy8vWHVTeEJpZUNOR094bGFIZjBHYmZB
        TFF4N2U1bloyaitMa0pCeThQYjhRTWhNYkI0Qm5yK0l2UitUMGU2S1FWckpvQUJj
        NERPc3l0MnZzQzdNZjQzSlZIc0ltVXlmV1g0V0R1eTdWZDFnS09UY25GZDkvSXQx
        ZnNzRjF2QXgrUGEyVVhLcC9yTW5jYm5mVDNTQUU4UUtPZkxjc05ueEExcTNIMXhn
        Mmp1bi9ISTRUOHV1Z2ovVkRIU2IwZzg2VFB0dDJEZWV1dnNPckpZUEw1ZWhJS1hV
        RlAwOFdSRENtekFoNmoyOWI0S21CRVY4RHN3YnhOSU5rNWgweDFRSkNxWmFvZ1RY
        NzVLSW9zUFNSbkxCQVBtaHNjeDZtWDJJcHh4NmtRV0l3NjMybmVVVWZpV2l4Ukwx
        OWh0OHJlNTJsRHg1dDlYUjlibk1XUXlMczcxZFF6TG9GVXhMSjlLR0EyK2VQazJa
        Z3FyakRnZ2RKbnBhSklUU3Q1T2w0YnRBS2o3SnhtM0hiVHpBRHR4bzlDc3E2KzEw
        RXhiTEF1ZmRJTm9rUGdVaEpwREF5YUJadWFSdEhMRmpuTjArSXhDckw2bVE4RkxO
        VHlpQkg4T3EwdTdiVlFaUEZqaXRvQ0xOa3hEUHl4NE9nNVljWWJ5MmJkVEUvTEll
        VVExWU9rbWhLWnErdnVjdXN4ZU1Va2ljTUtMbHJYY0lnb1BiRU1qMGV5c1k1TUhS
        Wis5T3VET1ZDM3IzNVVCeWVVVzRkdlpTamtNU1ZTTWtmWnlFdVFXMnJDZ1RGbElm
        M2F4Tnk1SmNST0taQzJuMHUwb1Z1YmpaVW9HL1lRMUZVR09mMG01K2o5THdxalhI
        dkIzTXpzUm5GY2kzUTc4dkpGL1dBamMraVdnY3BSVFVMQnFYdGF5aVA0SFpmTXh2
        ZmZPS3dRcGxGOHRxOE8wTDYvckpnYUpUSjNEdUpqSGlkVUVvRGRFamIxdXJQWUJt
        a3pmT25pd0h2Y09mQWRXdWJJVXhQMFNFRTY5Z09KRXN5MkhIOU9nQkpOZ2ZPZwpW
        QnA0OUdZZThtMXlLN1pSMmViZHhHWkpRVGloNk1lYmVJaEJQbEVHZGkwCi0tLSBt
        N1BmZWw5ZVljUi9kYXAvS0lia2FmVmxKcEcwZGF5S25zRE1TUDhiR0JZCt+MJpiO
        +4nLLc7hyvDD//e4yyoT63LXXZVaeLmjQd9ArIxoaZBl/pFoFh2WPrKUAbQ8O6h7
        SPyLTm5DK4B6D5M=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1zev40t6r439fzn9dddxrz5zq9vzzmq385rv59s9svf7qred0fqcsp4y2pn4rhpgjjgez862xf4rqyy2ytldkrw2g29fpesmmq7agzterhldmgsz3zjjwla5c7lq2hmac8d33vdg7js53zcrk8wtfzewq50ugrfzw3x0ghlrl0pmuhy3y8xhytgtyhfwqpup2gurfnkd8c2rq4q2w5zcvqg5h9ydcdlv4jhhkgwf2d39njwgc497vfd82fat4c50yedx2ajedtpeyrlqnf0fze8p0za3hypkzaqfnrhfx8zgrfp7qx3gzez6tf5vcpxyrzlup5evf0tqhtz30t4ckt9njc4vrw2mgtvxkl9upn9y34g2r36g4vvdy6mzse2vk5k26gym5cfr4ef65wvkhcv7yqag6mpfkqmxtzxe8yedhsnq2x9vuxqyx47rkvn5g0w6nf8yqs8t2gp5cp0kdxruesp0wh76n5wmm0ztx4pktwrharstredmlqeec22045wm3f9hhkz6fr4y94vzugr9ghaqhswrh7dx6yc9mc0y6u6drgtxesf0jsh89xg3u47yjvd3rnkdu22ls5j0hpcwymlr6gp8pt9qyc6swsczj50rq9rppsl6ufxv2kwcrmvtvn2svj56ryukk006l3wwe9plx6wz24y3xq0jje7rxkc86w59d0y6q2wf49whuzt28xf3zvmp25qwzxn4ms24pkw7g5w6xq5nnwyvanl72kqcztlssyjs9hzdrq2m268mktc8jhydnvezteghq40r0k772szggkhv8k8gvf0rn7346h0cv852cksx53tqdgqsfmjfsv6m6gcdhc4t059hx2gh4ckryzptper3hg3265usmnyclfjdxxr445602vr38xlywucmmxlrjf36nrn060jrtvqrfayc7tt96skkt754fqgj8zwd95cht9wz3x4ptsruceym727xv3fzqz56vt2my6slx2dwdpg962mpuxgdh3mz8wq5y3ymgcwakx9tjcge4ah6883qmhyevkvgay08t54x25yqkdtt2naspeyp97w04jjcv2kcgdzutzy5s23855aahl2q9rvwgc5cke56fg08x9v8mvydmgc48248hxx96ewjlhscl633afyaceeynk4tk2hvsuxd546ukp23s7crsj7rne2rqrxwkvkpld87z86wpcus2xf2h6cjr3xvcfrxqnphm08r3gxyn8g9v4sjztdv3p4qvfdk55sv66lryh5dmtxu99hwuexhpfyfz5496rawwc3rvtep4ylzgvaekhs4eadfzy6vckwpp37hd8q6xyvm2vcja69ppdzj62k22pg8u64l024skq3ejcgr3cqnfv5e5dzryxyr9qtc23t8pn0mhegj9caa89qnd6ck9xpsnfwlckz8xxykqf4egucryapssecetxt4e4q599g4a0y4ccswpykhsrd5wjvt32gtena5kg38yd04d4y3zhdjjlnp3tqwzux090268x3pvgqfyelr04ftnrjrk3hm9hrsg6gzex8qul3fu3uq8wg4aqr8vgeff5as5lcdq6zlkc3p9jpcdgar82wxxwgzevfju9uf8v2kqgjpfy5tsldv9udjsdaj2tf4uuknp0f6yksfznd8mtrmle0kjqa9qjeg7k8u8nll3k3qc0s0c9qxj7atp4janes0ud9ke9jljy3grf2th0my3eqcn4aumntx5276g3ccvy6ueujcvy8npz26x277tc995756rptur0jjwx06qeqpdcdguugnk083js8xf2q7gcsmtympfjvg8xrempvj29qrsaym3dqlkv3gjayelfnpl02acd3nsqv69jqg8ewkjp3spwnvc7ql05ke37utdttcgq0fhc8a4npxj2jhhdhazu494z4n772qq8wazqcc7qqvq0axs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-07T03:52:17Z"
  mac: ENC[AES256_GCM,data:BXqiqAfuc9Q7MscHG61h/FIFgtGLVddjUuIAqQyjytBrPNhwG6fFamUjYaZ275BDIMzUSwSymH+g0EtuehwvhrTiejnadSy9HtrcyjK3QJFSFKryU0CKIAxKlfaDgn83vmatrsua1KAI3prfZBrbsSWBel4JNYrItohymxZezv0=,iv:d689sFHo/Ln+4/FnSwem/9qkoSBCp8+s6cDhoaycvsY=,tag:7AQTwf7TuzBBy9NNaq6+gQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
