apiVersion: v1
kind: Secret
metadata:
  name: flux-webhook-token
stringData:
  token: ENC[AES256_GCM,data:Mo/hBDr9qaFROQIBlodehTpv3zclpWtbeVIHSJnbJ4o=,iv:hR5ZWpvvLKpWKIBeN1SX8iVeaIbwr/2Teb0BoTN/X78=,tag:heEiXFQBbAqOEckwFbFbRw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGVuUklMcmc1
        WFYwTW5OTzBUMWQzRVZIbWJDZkUwWjFJRTRBWisrek9LM1FYZjliYy9GMEVXMjlF
        aXRVMTJhZmlxdEVWaVdXUHZlL3oyWG9pRTVZMU84RlV4bWlFUUg5cTN2YmZYZXJn
        ZW96bHBYVjdKclk5M1ZZSHFLakJxUVY2U05YemRuODFZcWdFTzgxekI2SCtpY0VU
        WUpPSGMzNFVhQk5NNExNR2xLdExEeGVKTzh6akljT2t4L25QZnE4VGZqTHMwb1VV
        ZlpobEQ4Um9FUXVKdTJkakFES3dVTjRFaCtwVkRuVUtZT1JoZkM3ODBqL2lkeXNM
        MUZTc01JQlhZZHpyWmIxQ1hzVFRKTFE0cndyRm4yb1R0NVltNVduSnhCSWFscml0
        U21TMGRDdTQxR2hjNTdvZ2JrQXVuaEZrTzN4OThzNTBBTGU4aDRTc1NleUQ2bW1Z
        OGg4UzMvMFFlSU1IUFNlY1A2Y3kvRUEwempLaklTM0FJcWNTWUdxVUd0OWwxT2Ra
        eWZ1UVk3QllDaE5SZTA5WTVrcWdmREhEVXE4bGN1djdFeFZOeVJ1ZzZXSFZvWUVk
        aDNzUXdYRmdaVVR6bkc3SmMvbmJmT0kwRFhZQ2NpNEwxOVFIM09xcFRjRFp2RDFY
        SnJ3Z0hNamJWNWxpTTJ0SThFUWJEM0dCek40L0twL20wMlQyMUdhWkRNa2ZxdjB5
        NkljenNSclhmandjWXNibkkwaXJvL25PWEZVRzMrazZCc0dRRnFyQ0FuczI2NkFz
        YmtYVmhPYzR4QTRIaUMvYmZrZzJteURXbEdMN0VVR3pnL1ovTk40N0g2RS9xUU0r
        RE1vNzBkbEpXVDNYRktlNmlBNGh6VDRrV1MramNIejVTeis2bkpDS0J2eXAxQVFp
        eWtaS04wS2lnYWhSZzZCaGZ6aG5VTXArTWFRemgwYmpuQmMwSXpNY3pJSFhVajg5
        cWRNL0oxODhsVUVlaElROEU4VnpDUkV5eXh0dFlFZGZMMXF3L050NmUzb0VsS3ZR
        NUZoR2pXVXp6MU1UeFc3RCt6VEJrUnhXVGRSR0tjaytxUExuU3lxTXY0enRjL3Bp
        NEJVSlliQU9VSjhXWmJBb0hOYWtPMVFYRFJpbVNVQzFZaUNHUmpMZktLRGxrZnhz
        bldqSHI0cHVnVE9aRnJScFNMV2JHeDZzQWdZcHV2aytsZW5CRFNlQWd6Z1lBU3N0
        K2U4aDJlRDFQS3hKelBvNlJaUVlZUzlpcHRaNGIveGhYUlhFbUNGM2VhMmkzTkRP
        YmVMd01rMUZZMWlDaSt0cGZMcENzSVB2WUtRdlcwbktYN2VmV2g4SnNwMjVqR2lU
        bTR1bXhsM2U1VklvZHZWcW0rTnJBQXRSb1BrSmx1Mlo3aVdrU3VuVnh4ODMzTjRG
        Yy9VSEJROHdsZW1RSEg0K3VKQnV1enNDckFtTVFTV2FPVEJaa29zdkFYRXpCNS9L
        a1VyZXVpZVRCdUtDRGdKcW1tNVcyVHFyRzJBRkhjVlErR0ltL2NLZWFmYWcwenZi
        Mm03RUQrbGVRTlEyRlphZHUxM2Q1bHAvYUpaRm9DWVJOcU5LYUswVG5rUGRyTUR4
        MXFZWU1EZ0p4TzQwRFZtbGhqT1YwQkV0cERlNzJPYVp5aFkyYXhlMURNbElWSFV0
        L2F4UzJ5eGhCRDcraG1hNzR4anlrYXAvMVBKVk5oRy9UMGUweld3SG8zbzlHREdk
        cXN2cHdPSU4zZjlWL1Bva3ZySytEeTVlWlA4VlI0eVMwYUtXeE0zbFJCYkdsNitC
        MGcrZ1RvWFQwRE1IUmhGRjVva2pMWlk5OE5Bc3BMQVhHS01oT2h1Y0lFTUpYZ1Vw
        QlVEaTNxYnZtazFwZFR4OUJWam5HUG0xcjd0d01tQ0Jvd2VBMUJubnBKQnlNYWZ5
        eXJkRXFTTGUrcFhEcnA4OHlaanZzc2dUbnJxbnhHSGI4MTJFaTMyV2M2MzlSdwpj
        RmN3T1E0YUFBdFluNlpBdFFUczhhZGQzVXJDT1ZxL25qeTBGN0RPZFVzCi0tLSBQ
        MTduNzE3ZmN1d2pxb21vVjFLS1kzeTUxS0ZNYjB0c1c3UWRrWEZ3WEUwCnKHh24J
        JX2KTrxqyL9LhHxB7vYAcChXYes8YthgkzES0PExN9v754mfRO3zG/pal9iHdxtR
        AIu73yG5z+bY0Cs=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1zev40t6r439fzn9dddxrz5zq9vzzmq385rv59s9svf7qred0fqcsp4y2pn4rhpgjjgez862xf4rqyy2ytldkrw2g29fpesmmq7agzterhldmgsz3zjjwla5c7lq2hmac8d33vdg7js53zcrk8wtfzewq50ugrfzw3x0ghlrl0pmuhy3y8xhytgtyhfwqpup2gurfnkd8c2rq4q2w5zcvqg5h9ydcdlv4jhhkgwf2d39njwgc497vfd82fat4c50yedx2ajedtpeyrlqnf0fze8p0za3hypkzaqfnrhfx8zgrfp7qx3gzez6tf5vcpxyrzlup5evf0tqhtz30t4ckt9njc4vrw2mgtvxkl9upn9y34g2r36g4vvdy6mzse2vk5k26gym5cfr4ef65wvkhcv7yqag6mpfkqmxtzxe8yedhsnq2x9vuxqyx47rkvn5g0w6nf8yqs8t2gp5cp0kdxruesp0wh76n5wmm0ztx4pktwrharstredmlqeec22045wm3f9hhkz6fr4y94vzugr9ghaqhswrh7dx6yc9mc0y6u6drgtxesf0jsh89xg3u47yjvd3rnkdu22ls5j0hpcwymlr6gp8pt9qyc6swsczj50rq9rppsl6ufxv2kwcrmvtvn2svj56ryukk006l3wwe9plx6wz24y3xq0jje7rxkc86w59d0y6q2wf49whuzt28xf3zvmp25qwzxn4ms24pkw7g5w6xq5nnwyvanl72kqcztlssyjs9hzdrq2m268mktc8jhydnvezteghq40r0k772szggkhv8k8gvf0rn7346h0cv852cksx53tqdgqsfmjfsv6m6gcdhc4t059hx2gh4ckryzptper3hg3265usmnyclfjdxxr445602vr38xlywucmmxlrjf36nrn060jrtvqrfayc7tt96skkt754fqgj8zwd95cht9wz3x4ptsruceym727xv3fzqz56vt2my6slx2dwdpg962mpuxgdh3mz8wq5y3ymgcwakx9tjcge4ah6883qmhyevkvgay08t54x25yqkdtt2naspeyp97w04jjcv2kcgdzutzy5s23855aahl2q9rvwgc5cke56fg08x9v8mvydmgc48248hxx96ewjlhscl633afyaceeynk4tk2hvsuxd546ukp23s7crsj7rne2rqrxwkvkpld87z86wpcus2xf2h6cjr3xvcfrxqnphm08r3gxyn8g9v4sjztdv3p4qvfdk55sv66lryh5dmtxu99hwuexhpfyfz5496rawwc3rvtep4ylzgvaekhs4eadfzy6vckwpp37hd8q6xyvm2vcja69ppdzj62k22pg8u64l024skq3ejcgr3cqnfv5e5dzryxyr9qtc23t8pn0mhegj9caa89qnd6ck9xpsnfwlckz8xxykqf4egucryapssecetxt4e4q599g4a0y4ccswpykhsrd5wjvt32gtena5kg38yd04d4y3zhdjjlnp3tqwzux090268x3pvgqfyelr04ftnrjrk3hm9hrsg6gzex8qul3fu3uq8wg4aqr8vgeff5as5lcdq6zlkc3p9jpcdgar82wxxwgzevfju9uf8v2kqgjpfy5tsldv9udjsdaj2tf4uuknp0f6yksfznd8mtrmle0kjqa9qjeg7k8u8nll3k3qc0s0c9qxj7atp4janes0ud9ke9jljy3grf2th0my3eqcn4aumntx5276g3ccvy6ueujcvy8npz26x277tc995756rptur0jjwx06qeqpdcdguugnk083js8xf2q7gcsmtympfjvg8xrempvj29qrsaym3dqlkv3gjayelfnpl02acd3nsqv69jqg8ewkjp3spwnvc7ql05ke37utdttcgq0fhc8a4npxj2jhhdhazu494z4n772qq8wazqcc7qqvq0axs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-03T20:55:55Z"
  mac: ENC[AES256_GCM,data:dnTyjLX83RH0uxETy7nPrAQjxSYzbP+ODvPSpj50KygSr89QwmrfLMRSccTJwhaWPT4FZrLTmfzvoBitjwzSfBM09A8vxWS23h2T1L60c04+dSEogTwlpmdWxBtw8gwacOBwl+Ov463vacg8GMNvT93kaY458nbNiDghXGJM7WM=,iv:7LBZWj+OCc1WMZhUdtkfwN8xn64Oy5hGvjUEJZLR7/U=,tag:Q/inUAoMwsvEkuNEjsh88g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
