apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Mp7zbvkaV8ZBLw/WN4jLPBrxVtaUkbfZSJklrxtcaSDcbpHrRpelWgErCYb2ArA3/DpHzIkSBxtzIDnUPOpm6g/JosLnMiAN/4AMnWqGknb8DdbYCOkU6ul7fIz+rizxpCVFsPYTyA85z7Yf02vF7tkLoK73Tjg5oPRz5j9REs/meOdxU9xR4UC4VDy9224MY/QUNrTmSsgQPXyQpCLOJbNCCQVQCs43BwTWb2tzg1i9O20G,iv:tAF77AYXBpHfwrIALyoJewjxLte1TxW0RRXOF523SC0=,tag:CUQvkTO18EeXbdj0XrtPXA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHQ0SGZMakpP
        YkI2ZWZGdkhUbEZFTlBTaXdvd1M5dzBlYXBUVlo4V2JrUW9jQ2dOUXRHT0hvQ3lK
        UHFTOXcydVAvZ0hWemZUR05zekVGd1FSbG56c2NOT2dTd3FET1cyL3ZxajkrSWIv
        Tjk2OEpEQWVWQ1VjMWlxcWtVcFJWWlZkUVpqUXZNNENXS29Nd2VKOTAwbVZwZ3Ir
        aDVSUHQvTC92YlF4Rm5OV1hiTmNTZnpaVlBYc2hIckFHMGp2c21uRHJlcS9IWVI5
        ei9GOVUwdnhSNlNnOUJKdVNmK1g1NzB0YTVkTkFldURJUGRNQmh1SWdkbnBOUjRp
        ZzUzeHZVNzd3b3I5MHRvaFN6Z0JWOEV3M2R3TU1NYTVoemp2cXFweTVDb0hVZzdN
        K0FyQmp4MjRMWUpuSjVNQ1EzZ0tFWktGdzBnbDB2M2NHeTdaczh1azBmNjZ5RnBj
        Y0FhUEZMSGR0bVEvOWJWWS9SNWcwZFhzQ1R0c2YvOHBwY2N5YXRGeDNHMlRWL0NK
        bHdsSWtPS3hxdlJ2S1BLWWo2b3lWSnd5S2llTjRmMkk5TlJsRWJrcVFhdUhpS3NR
        R2VmYU1mSUVMWTBGbE9qeDdJZnNPbFZSanpJa0dBa2RtOXV4c2x3ZExBd0JWTUkz
        TVIzOGhQMmJFYmQvTUJrUUtZNFRpOVNUQlJRbXFUblZSaERteDQ4aE1TZUk2WDRP
        djNKTFBSN3B2YmkzdU52NlpLRGdTY1o0Y3pJNnNqRGV0QnZFTThOT2lpUnNWaUdq
        WGVWZm5HR0dOK0dFUU1zMVhNdDg3NzlaazBCdC9walViajhwcUZINkZXdjFNS3lh
        eUgyRE1xWU8zaXJrNHpTY3BPZytCVXh0OXphaEd2Y3JlTzRPdnhSV3FRK2Vod0lE
        WkxjKzB6UGVaVyt2eURNRDJrWEZGZXRQZS90Q0pJUERFdWFJRXlBck1yWmgvbXV2
        U2VSdXdnU2JBSlV0OU03eGxsOHA4SzgxY3dFRm54UnVIeTBzWnhQRm1oaENzVzVH
        YzFzU3c3YTB1WlI3b3p0NjIvWlM1Q1ljMXVkUUR4YUFVdFVBcDVmS3NEanF5VGFE
        aHVaaWRoNDVpTWROYzI0UlBWbDZlME9yajJRSy8rRG1kYWc3N1FDY250WldvUWR1
        U3VrNGo5SXgvOUlwdEFCSlBlQ1crSXhYS0U5Q0luR0ZsQVRjVXh6YlFNZmRnSEFD
        bi9oMzZIcG0vRkNKYmNCSXQ5dzBmcXJVNUJneUd0Q3pQSWtJamp1MjFucm1zYjBr
        c3dvZ2M1b3RjZkd0b1NwVGwxWnFLMEE2c21mSDdBQmlMSmE5M3RPRHUxMUFMK0c0
        c3RsZjdvd2dFU3U0WHdFK21iSFRodE9hSHlvQ0J6Y3pydTRBam1LVlFLSVd4YTNT
        MTFjQWVnNkN5Y08xR0tIYWk0VTE3dFhMamxNTXFnYkl4cENmQ1lLeE82Z2twNlNQ
        bmkvNTdjOGNNSFNYbXh5OTlEYnN6WFlVQm16RFE5YmJQbTZ1M3ZtVUI4U2VYNHow
        eGZlSW53WW9uSzdDdDR5aWZaTnpKMHNEK0trM3hVT3ZEWnFUWUFXVDBxRzgvWGRN
        K2ZmcWFGcU80Z2dLd2txMmplR00wc3k2bmt5L0RBS1c0MVkrYTF2dWp1QmlNSkk3
        aUJvVGY5YTV1YUh5WElkaFlJenZqRStoTXpldURHam5aZUI2K1NPbXYyVEhmSzJM
        RC9oVE1uSm1KYlEwamMzVTM3U3lGMTUzdk1sWWsxOHZmTEZPTWVETVlyRm02bndM
        M1JNVDVFVlcreGV3azZuUE5xUmpUaGlOMU1xMElwdGVDOU90VUsxekpPWWN1U25Y
        dmNaUHoyT1krK3BBM0lERHNhT1Bkc3p3OXZ3cGlUaDBTWFV0TXZwNzJCVm9uNFZN
        dFMrN3ljWXJzYmVnTmd2SXYzMEFqSWtRWTZDSU5nRWpYVDdVdFdVMW05bERVQQox
        UDgrMDlvV1A4QnNvSUFuZmZhTGZXQTZ6RUR4M0thZWMrV3JQdVdaNDNNCi0tLSBU
        YjduTFM5OStoRUZOeFRtK2ozUWlsRVVMUU9BSGVLVUNkZHg3V240bC9RCviQ2MRU
        7BzHeIaf0hoqgYQAsGCl3KMj4LIN1Ve9EFxnvjhQ6j4CT5zxRGUKDPq+RLZnktMU
        rWOyiAxmXrWnFbM=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1zev40t6r439fzn9dddxrz5zq9vzzmq385rv59s9svf7qred0fqcsp4y2pn4rhpgjjgez862xf4rqyy2ytldkrw2g29fpesmmq7agzterhldmgsz3zjjwla5c7lq2hmac8d33vdg7js53zcrk8wtfzewq50ugrfzw3x0ghlrl0pmuhy3y8xhytgtyhfwqpup2gurfnkd8c2rq4q2w5zcvqg5h9ydcdlv4jhhkgwf2d39njwgc497vfd82fat4c50yedx2ajedtpeyrlqnf0fze8p0za3hypkzaqfnrhfx8zgrfp7qx3gzez6tf5vcpxyrzlup5evf0tqhtz30t4ckt9njc4vrw2mgtvxkl9upn9y34g2r36g4vvdy6mzse2vk5k26gym5cfr4ef65wvkhcv7yqag6mpfkqmxtzxe8yedhsnq2x9vuxqyx47rkvn5g0w6nf8yqs8t2gp5cp0kdxruesp0wh76n5wmm0ztx4pktwrharstredmlqeec22045wm3f9hhkz6fr4y94vzugr9ghaqhswrh7dx6yc9mc0y6u6drgtxesf0jsh89xg3u47yjvd3rnkdu22ls5j0hpcwymlr6gp8pt9qyc6swsczj50rq9rppsl6ufxv2kwcrmvtvn2svj56ryukk006l3wwe9plx6wz24y3xq0jje7rxkc86w59d0y6q2wf49whuzt28xf3zvmp25qwzxn4ms24pkw7g5w6xq5nnwyvanl72kqcztlssyjs9hzdrq2m268mktc8jhydnvezteghq40r0k772szggkhv8k8gvf0rn7346h0cv852cksx53tqdgqsfmjfsv6m6gcdhc4t059hx2gh4ckryzptper3hg3265usmnyclfjdxxr445602vr38xlywucmmxlrjf36nrn060jrtvqrfayc7tt96skkt754fqgj8zwd95cht9wz3x4ptsruceym727xv3fzqz56vt2my6slx2dwdpg962mpuxgdh3mz8wq5y3ymgcwakx9tjcge4ah6883qmhyevkvgay08t54x25yqkdtt2naspeyp97w04jjcv2kcgdzutzy5s23855aahl2q9rvwgc5cke56fg08x9v8mvydmgc48248hxx96ewjlhscl633afyaceeynk4tk2hvsuxd546ukp23s7crsj7rne2rqrxwkvkpld87z86wpcus2xf2h6cjr3xvcfrxqnphm08r3gxyn8g9v4sjztdv3p4qvfdk55sv66lryh5dmtxu99hwuexhpfyfz5496rawwc3rvtep4ylzgvaekhs4eadfzy6vckwpp37hd8q6xyvm2vcja69ppdzj62k22pg8u64l024skq3ejcgr3cqnfv5e5dzryxyr9qtc23t8pn0mhegj9caa89qnd6ck9xpsnfwlckz8xxykqf4egucryapssecetxt4e4q599g4a0y4ccswpykhsrd5wjvt32gtena5kg38yd04d4y3zhdjjlnp3tqwzux090268x3pvgqfyelr04ftnrjrk3hm9hrsg6gzex8qul3fu3uq8wg4aqr8vgeff5as5lcdq6zlkc3p9jpcdgar82wxxwgzevfju9uf8v2kqgjpfy5tsldv9udjsdaj2tf4uuknp0f6yksfznd8mtrmle0kjqa9qjeg7k8u8nll3k3qc0s0c9qxj7atp4janes0ud9ke9jljy3grf2th0my3eqcn4aumntx5276g3ccvy6ueujcvy8npz26x277tc995756rptur0jjwx06qeqpdcdguugnk083js8xf2q7gcsmtympfjvg8xrempvj29qrsaym3dqlkv3gjayelfnpl02acd3nsqv69jqg8ewkjp3spwnvc7ql05ke37utdttcgq0fhc8a4npxj2jhhdhazu494z4n772qq8wazqcc7qqvq0axs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-03T20:55:55Z"
  mac: ENC[AES256_GCM,data:w4F0ZfkiupdAhSMY5LU5QdFn6xZHSpqR4Oo4ZacCE5oboAcgCb45TiUaYUYHhuVIORvZ1JumNCqk4qEMnXwXv7FaDplGJ7xF3azyaJJf47K2x/DN6nP3gZHONABWntG7gsibUvevwiKd+H4DUSh29BlWSkVghdd7mU6IgwYuBy0=,iv:KOT0AZcMFQejhQF2cSIncbQXpp5Q0yUpDuxIscirprA=,tag:LlNqUscA6QKZtXRDruiDrg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
