# The secrets are a whole values document because Flux splits a targetPath
# value on commas. The two addresses are here to keep them out of Git.
apiVersion: v1
kind: Secret
metadata:
  name: matherlynet-secret
stringData:
  values.yaml: ENC[AES256_GCM,data:pLQORpZTk4Hk1CgN9TF1X17LphRiSxx4vN0kl/6mATV22BZhKWJ9acoW1ky6MfgxuaEvjTtRpvQgJ/LB5IS4LzAfkQfwYCRFPSatQr6nZ793qFLiGbXp5s0QTey81uHTyMhV+sZXLkWQRfFKR2vIyai4CDi6NmHXHVpRA/FTGvAzztCpNfqET2dqoPE7D9hZnG5RBfFKRTo1bfwKkG0oVA/lTu5oHkiPG0Yrx+8xJhpgJsAiQvsqcpRneMLqFrDavT5EYaOf7B0pExniXIBpJDBvh2vTy9Wq1lUPsuAOWhxhZBa9UYbsSXSvj2a3GvHb9dgJxwkqlwPCa65hcFdeggY4ZvXxWjM+6r+XP8Nqq6QqKYWlw5mW91zXetBRbbcsOJBBFKhFJzcRDOQQZLQcnZSFKkYnqfQbhW0hL6LnpwpP5ymVZJ9DztckxHV602UZJNZgRLi/YgMMOFRG35cLeHEPFZVANid2wBhwj83LvdbLC1Pe,iv:PcFXaNbgiPGlUpsslTJ5wG2n4so6y4N57P3zaDw8ru4=,tag:hRV5Dfkfzl5+gOxzk32dQw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHQwWjBoZE9j
        TG5BaXA4Q0dQQ01GVWNLWmJVbTlkQzcyV0JaQkZ3OURYVU42V3FBOFJPek9BS0o1
        Vnphdjl0KzhObks2OTk5MDc1bWpHVzlvdDNHa2dTb0FnVGVQUXFPK3c3VmdzOGpV
        bC9DdjRyM3hWUnhTYUZrSnpKNHRPUGZuRTJHd0ZMS1BNZVhQUHVQOWhmSFl5aUcz
        Rk5EZkNXNmx4Vk1OS3FTQXZBRGJKYmFtZEx1YmwvQ0NJWFFUd1NkeXgwTTNIR2tP
        UUFzaGUyaWFBOWZNU2tHZEFjUVVxc0tLWmc2RHlwamp5bWFrbjg5NXdLT1IwR2tT
        Sm1HREFLQ1p3R1VEcWxIVjFxb205ZjJJQlBlS1VoUCtiRDkwS2JMUUtrUnhmaytz
        YWIxQlFLTEJ6a3c1RWJqMmxid21KYUtCZjZaQkg0OVlYTEtKTEI0V2F3TFVZRkZp
        WlczSGtuUCswbUdONjltY3gwSkJCclVhLzNEOVhwcWtnZmU4eEYrN2F1TFFzTnFs
        RHpZaGRpdktpL25zWWJ1UmhUR3lHL2N4VjZkbTMxUW8rbm5ZclZrK2RyME1nMmxo
        QTV4TUlxYm9ySE1EbXNXUVh3Y2Q0enE0UzB5YXRNSnFKWU1qZElwZUcrMUJVRm1V
        UGp0TzUzSm1RYU1PN3A4SUxyOEM5Y3Bia2NQb0daL3N5WVFhV1laOVUrNTRacjRU
        NU9YRStSaitVY0xlSGNsTDdkdlpyeCs1SUZKTTUrU2MxejdpSVdaTFlLanU5TEZr
        VmFWTzhBam1ENkNCMXF2VnVpcXM3cGdIT2l3c3RNZVZaTU9uYVZtRE5KNHlXZ1BT
        dUpFbzY1L3psWHpkQTRhOS9pdXJ6cEQrOGZuZFp6L3NVVTdISHJLWnBmMVE3WGJY
        OVFWd1Z6SWtjaCtMM3k1MkpNZm9YVzAvVnhYMTN6c3pWOXg5cmJBd0ZITWNkaW1h
        eEI2QVgrYVJaeFJiVHNHREQ5OFUwbWdpcFl4SDcvcEFNcytMRUJ5d21xUk1NZHBr
        UVhmRmoyZENTVWkxM1ZjTy9YeTNGTnNvNm9ZT0dNa21zd3F6WGNWRXVLYXA3TjVw
        bHhXZ2pYMjlmUmxVOWF2cEgzVVJqZ1hySXNoSTZZR3BqZTl3Qyt1QklvSzYrTTU3
        TmJud3crcW5HbXprZUt3MVZlakJ6a3V3cmpMaC8rK3NMMlNWR2VZZW42S2w0cHVy
        NTMxVnYxVjhGdW5JU0xXQ2QrZ24vV1BRbjZMNXRmTXR3OXRYT1NHSWpXLzBVbmgx
        ZmhNTStOTHJ1NWY3VC8vTFRvUGI5bGUxRlp4dkdNOGVHS2RDU0g4cmI5ZlJ6c0xn
        cG9GTVBkT1ZsczQyRjJnbW1CRmd2SWkxbGpuOG8yd3VDL3lJdjFHbjlJbGJKbVJY
        QmttT2JybndPamJNeXlrRW5hdXg4NFIyL21wbm9CMlp0WEc1a096TkxLenhjSWFv
        eUtzUDZnY2pFZS83cTJ5VW9YVHdwK1FSTTl2K2F0SEJmenF5c1h0TVZDVFZ2dlYx
        MHBQYUxuS3pmUXRGV1FnWWp6M0FWMjlTbWZZQjZWeFRJMHJ3TkxmOWd3akZZS2Zp
        NkdwUm0rcGhiRDJ6SUJ6Sm43TTVDaHRvamRCUFE5SUxzS2xDd0ZKK1hvRzhxa0Ns
        aG84L25LM2JBNlBSdUlrZmZzZ2szRXZhVjFEV1NDekE2RlNEQ1JBN0ZZK3NYdzk5
        Q3pqTWVqV0w4MjFFL2JwaGpGQ2M0YzlRRklBcE95Z2xLOVU5SDVoYVF5L0tySnhh
        Z0dRTkFkeVMrWHZ2OFZTK0REYTVYbkdPM2pFNEpBdWc0T2NHaFBUMjkrczNONDRV
        Mmk2Sk56UjE2Rm5RVUhPZHBDQk9tYWtmNzd6S21FbG82VUo5bTdkc09UR2lOSUQr
        Q282WTY5clk5NzBnMVhYTytlMUozclZ1TzZLY1JWQkVxWlFuQkRZMG0rSjVmdwo3
        OFJDZmxXbXdxc1JpUnlYTVFGZTJLME5UeTFYVWtMalRlb2dTOVgxL0FJCi0tLSA0
        RjV6Q3Qwc0J5REVXRHRnMlVjckVBTXZJSnluUTVkTGJqWGFhQUZwa28wCkqlVr6S
        8dJ79fmW02F723k7TeeB+HfxV/ruPEQ6zDeTz7SC2NUoGTJ1UxofHpbC1Db8HJrZ
        rvMWDFkkna1W6ig=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1zev40t6r439fzn9dddxrz5zq9vzzmq385rv59s9svf7qred0fqcsp4y2pn4rhpgjjgez862xf4rqyy2ytldkrw2g29fpesmmq7agzterhldmgsz3zjjwla5c7lq2hmac8d33vdg7js53zcrk8wtfzewq50ugrfzw3x0ghlrl0pmuhy3y8xhytgtyhfwqpup2gurfnkd8c2rq4q2w5zcvqg5h9ydcdlv4jhhkgwf2d39njwgc497vfd82fat4c50yedx2ajedtpeyrlqnf0fze8p0za3hypkzaqfnrhfx8zgrfp7qx3gzez6tf5vcpxyrzlup5evf0tqhtz30t4ckt9njc4vrw2mgtvxkl9upn9y34g2r36g4vvdy6mzse2vk5k26gym5cfr4ef65wvkhcv7yqag6mpfkqmxtzxe8yedhsnq2x9vuxqyx47rkvn5g0w6nf8yqs8t2gp5cp0kdxruesp0wh76n5wmm0ztx4pktwrharstredmlqeec22045wm3f9hhkz6fr4y94vzugr9ghaqhswrh7dx6yc9mc0y6u6drgtxesf0jsh89xg3u47yjvd3rnkdu22ls5j0hpcwymlr6gp8pt9qyc6swsczj50rq9rppsl6ufxv2kwcrmvtvn2svj56ryukk006l3wwe9plx6wz24y3xq0jje7rxkc86w59d0y6q2wf49whuzt28xf3zvmp25qwzxn4ms24pkw7g5w6xq5nnwyvanl72kqcztlssyjs9hzdrq2m268mktc8jhydnvezteghq40r0k772szggkhv8k8gvf0rn7346h0cv852cksx53tqdgqsfmjfsv6m6gcdhc4t059hx2gh4ckryzptper3hg3265usmnyclfjdxxr445602vr38xlywucmmxlrjf36nrn060jrtvqrfayc7tt96skkt754fqgj8zwd95cht9wz3x4ptsruceym727xv3fzqz56vt2my6slx2dwdpg962mpuxgdh3mz8wq5y3ymgcwakx9tjcge4ah6883qmhyevkvgay08t54x25yqkdtt2naspeyp97w04jjcv2kcgdzutzy5s23855aahl2q9rvwgc5cke56fg08x9v8mvydmgc48248hxx96ewjlhscl633afyaceeynk4tk2hvsuxd546ukp23s7crsj7rne2rqrxwkvkpld87z86wpcus2xf2h6cjr3xvcfrxqnphm08r3gxyn8g9v4sjztdv3p4qvfdk55sv66lryh5dmtxu99hwuexhpfyfz5496rawwc3rvtep4ylzgvaekhs4eadfzy6vckwpp37hd8q6xyvm2vcja69ppdzj62k22pg8u64l024skq3ejcgr3cqnfv5e5dzryxyr9qtc23t8pn0mhegj9caa89qnd6ck9xpsnfwlckz8xxykqf4egucryapssecetxt4e4q599g4a0y4ccswpykhsrd5wjvt32gtena5kg38yd04d4y3zhdjjlnp3tqwzux090268x3pvgqfyelr04ftnrjrk3hm9hrsg6gzex8qul3fu3uq8wg4aqr8vgeff5as5lcdq6zlkc3p9jpcdgar82wxxwgzevfju9uf8v2kqgjpfy5tsldv9udjsdaj2tf4uuknp0f6yksfznd8mtrmle0kjqa9qjeg7k8u8nll3k3qc0s0c9qxj7atp4janes0ud9ke9jljy3grf2th0my3eqcn4aumntx5276g3ccvy6ueujcvy8npz26x277tc995756rptur0jjwx06qeqpdcdguugnk083js8xf2q7gcsmtympfjvg8xrempvj29qrsaym3dqlkv3gjayelfnpl02acd3nsqv69jqg8ewkjp3spwnvc7ql05ke37utdttcgq0fhc8a4npxj2jhhdhazu494z4n772qq8wazqcc7qqvq0axs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-04T21:54:13Z"
  mac: ENC[AES256_GCM,data:KQsws/KwcyiDsBBO0AqOFo/zjFchGMgGEKSM40+rbjbvZwnHqpth2kx1Jq/pHhNmd3hylwDQFkZl7uQLNICUR3cjtUxmHeXs+0fDtq3wxVonOAxC5aouIMvvn7juMhIXHkbj5w0xvCMQz01o30MXQW/M3GE/vNOtQLtcBFVv/Rs=,iv:gAUbj5y2/EJnt8BYptCuuXTqes9RLdUP2+ZgEY650cc=,tag:FTn56IMcEKthjqT0NQ8oBQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
