apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:WyPWIMqJr7M2PrbSXEsm8WiPtb+/x7dJrFH6St+h5NguIWflAgPKUWloxZpKhNR8IabjZ+Y=,iv:rLTlIZCyDW0SoJKJ6allwHusSqXtVSgeHsvxoJP+sE8=,tag:XENFsov6Sl4v844H1ieiXA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGQrZnhPUGFu
        c2JyMWZiR1RBTmFIUGxDemVIWFdlYS9qYlU0LzNVd2UrWm4ranAzaFVHRHZyYkty
        NzRhZXJWajB6VVNTZ3RkcUN3NDhDT0FVNzNOZkNpOW9RWXdXNFQ4anRNQW1uMmw4
        QWVQSzBaUUtqcGtZS1V1bklRUERod0pmR3VidC9vWU1laFJlNVRuck5oMkIyUWxV
        UW93LzZ3TG8wVm1hMWZmaDJzR1lNOE85UThIQWQ4anFUeUFlZW5BM1E0c2dleExv
        OTRiSzVZbkJKZnZYV1lMeldEUTE3MTFTRTVjcjN2M2dwM1BKbTIxVEZWOWRWTFlK
        VnVNRG5aTms0Q3FnVjBRYU16M0NpYnlwczZKQWhNNDZSOEZ5ZlVZUlp6TFVqQWtk
        NWdMZFhMaC9TbGNvTkhHV3dYYzdDNy90UkI5RXVLT1JwcTA5MnpGTkVmL1FTNCs4
        YU9Yb3EvNTFUUWxtNEJMdkpReE9HUzBobzlyMjV3azdCUlF3aFZmdTlOUjV3aHpW
        MTZKaXZLa0pPdnk1MjlucjVmMkhnVkQ4Qk1yT3lOOE5oK3hzM0hWMFlyVm54b1Ar
        MG52L2NKOStjQkpLbzJrZFVQKzhqMXNZRG1wTE93MTl5cTBCMHJlUk45UWRCVmdp
        ck9RRHRMQ3V3UEJyazU0bkR4VXBPNktza3E4ZUlDLzFXWmVoTzhRblY0bCtSc2hx
        N0htTkpUeUVRRGJpOTBhWXdMQ21HYnoxZk9pV2xLZmc1QnJWSkFiN0ZUZ1BBMENs
        MHc2Um1kaXFxZ0QzTVdaYzRsYVFTY1QweTkrK1JSOURyNHQzMG05emFWUjZ6N2Q2
        dVhoZkhvams0dFBuMEdIbDM5OU5JN0xUSkx0VGdJNzlpbkU2Y05pOVZKYnZ4WFpP
        RlhGT1lCNld2T0RzQ2R4MlkxUCsvejRXU3AxOG42dWtQYUJLSU5MeVhadEp0djQx
        WkZ5azQveFhscm44UkVocTduVjBKaFJNY3RMR1FGY1I0V1VKOWt1cGRRbXN4cnFZ
        V3VkZnAxSEk0SnpaaDBKNXgrVFFvNUljcXFPUWZ6Mm1WbklRaWEyTGRMUG9YZnpF
        Q2ZEeHRDaHpUbGVmMVRnVVVXK09yUmtobDY2bUdOMm9jTUl5bVNGZzhvWWRFc0lu
        RStraHJLK0VjdWhMVzJOT0NpYXdDT0NhVXNxNkRoS2lkL1dURjdMOW8yOHhGeWlm
        UWxCOGdHNjVKODZFS3RNWWpsdkVteTMyeVpEMHNQakdUZEFGc2JXQ0gwWElZMFI5
        d1duQUl0ZmROdWxUSjFDSTFaOTZXSUJaQjZKblZ4RXFEMHl6WldKVWVVNk5wOTUw
        amZ0ZHozTWVlRG1HMHIvbjU3QUlYTE1kRWt4elRyR2xwQVJsbWZJcU4zWGRycUlO
        WVJkd3I4MkY3SWs0WUh0WXQrMWQ0QnFadm15bXkyNzVROWVidndIS3h2ZSswckY4
        T0l0RFdKMmk4dVFKM2N4K2tLaUtxNy9DSE5mUEg2Y2piQ1hQMWtpQU8zdEpiUWVw
        ZE5GZUR4d3dpNWVVSDRsUXZtQXZsOUpxUUlhKyswanNscURIZmZSRXYzb05pQUhX
        dVpVVmo2c21qejI4M1ZZWGV6b2FEcWtGaFpNUUZzMWdWanR4c0ZMbUdYVkUzNnox
        Rm0vYkhSenFKU2dPOFhUL3U1dFVtNHRxUUs4S2l5NlQxY2Z1MW5WV1pxeGRGTWpu
        cHB3N1FVYWRRQjZtR0l1T1VTa0N5UGFHV28vVmJyTElpbTFzczNTbThOMXRpN3Ro
        QTZzUFhFaEFpTGxnNDBXYVp0bS9oUjI5QTJnWkNCZ00wY2l1Y3IyRThwTFRCelF0
        dGFCWldNazRMOEJwK0hmSW1xS29yZ1ptd2M4RU9EclZCa2Jmcy9MMUZTckhlQTNH
        YVdldFQvZFFHQTFlZEQ1T2FDbTJyeEt4S3ZOUDVPdlFQR3lJUUlWeHpwY2hUUQpn
        K2VuZmJZVGpFU2ZJL0wzNW5pODRmZkUydW91TnhURFJKSjVLTXJ6SGNJCi0tLSBG
        Z3ZSK3liNVE3MUNaUVpFalNEQVBlcXdSYVV4ZkI2N0x6OTRRZzVWaUpRCgZXV8p2
        sjqTDxUNdAZ3IySk7r18Hbw5qjtaWbIeBWng7pRx9vtisfwCaNDbZbErXyTAC67A
        TOx1P6G+ZcFVa4U=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1zev40t6r439fzn9dddxrz5zq9vzzmq385rv59s9svf7qred0fqcsp4y2pn4rhpgjjgez862xf4rqyy2ytldkrw2g29fpesmmq7agzterhldmgsz3zjjwla5c7lq2hmac8d33vdg7js53zcrk8wtfzewq50ugrfzw3x0ghlrl0pmuhy3y8xhytgtyhfwqpup2gurfnkd8c2rq4q2w5zcvqg5h9ydcdlv4jhhkgwf2d39njwgc497vfd82fat4c50yedx2ajedtpeyrlqnf0fze8p0za3hypkzaqfnrhfx8zgrfp7qx3gzez6tf5vcpxyrzlup5evf0tqhtz30t4ckt9njc4vrw2mgtvxkl9upn9y34g2r36g4vvdy6mzse2vk5k26gym5cfr4ef65wvkhcv7yqag6mpfkqmxtzxe8yedhsnq2x9vuxqyx47rkvn5g0w6nf8yqs8t2gp5cp0kdxruesp0wh76n5wmm0ztx4pktwrharstredmlqeec22045wm3f9hhkz6fr4y94vzugr9ghaqhswrh7dx6yc9mc0y6u6drgtxesf0jsh89xg3u47yjvd3rnkdu22ls5j0hpcwymlr6gp8pt9qyc6swsczj50rq9rppsl6ufxv2kwcrmvtvn2svj56ryukk006l3wwe9plx6wz24y3xq0jje7rxkc86w59d0y6q2wf49whuzt28xf3zvmp25qwzxn4ms24pkw7g5w6xq5nnwyvanl72kqcztlssyjs9hzdrq2m268mktc8jhydnvezteghq40r0k772szggkhv8k8gvf0rn7346h0cv852cksx53tqdgqsfmjfsv6m6gcdhc4t059hx2gh4ckryzptper3hg3265usmnyclfjdxxr445602vr38xlywucmmxlrjf36nrn060jrtvqrfayc7tt96skkt754fqgj8zwd95cht9wz3x4ptsruceym727xv3fzqz56vt2my6slx2dwdpg962mpuxgdh3mz8wq5y3ymgcwakx9tjcge4ah6883qmhyevkvgay08t54x25yqkdtt2naspeyp97w04jjcv2kcgdzutzy5s23855aahl2q9rvwgc5cke56fg08x9v8mvydmgc48248hxx96ewjlhscl633afyaceeynk4tk2hvsuxd546ukp23s7crsj7rne2rqrxwkvkpld87z86wpcus2xf2h6cjr3xvcfrxqnphm08r3gxyn8g9v4sjztdv3p4qvfdk55sv66lryh5dmtxu99hwuexhpfyfz5496rawwc3rvtep4ylzgvaekhs4eadfzy6vckwpp37hd8q6xyvm2vcja69ppdzj62k22pg8u64l024skq3ejcgr3cqnfv5e5dzryxyr9qtc23t8pn0mhegj9caa89qnd6ck9xpsnfwlckz8xxykqf4egucryapssecetxt4e4q599g4a0y4ccswpykhsrd5wjvt32gtena5kg38yd04d4y3zhdjjlnp3tqwzux090268x3pvgqfyelr04ftnrjrk3hm9hrsg6gzex8qul3fu3uq8wg4aqr8vgeff5as5lcdq6zlkc3p9jpcdgar82wxxwgzevfju9uf8v2kqgjpfy5tsldv9udjsdaj2tf4uuknp0f6yksfznd8mtrmle0kjqa9qjeg7k8u8nll3k3qc0s0c9qxj7atp4janes0ud9ke9jljy3grf2th0my3eqcn4aumntx5276g3ccvy6ueujcvy8npz26x277tc995756rptur0jjwx06qeqpdcdguugnk083js8xf2q7gcsmtympfjvg8xrempvj29qrsaym3dqlkv3gjayelfnpl02acd3nsqv69jqg8ewkjp3spwnvc7ql05ke37utdttcgq0fhc8a4npxj2jhhdhazu494z4n772qq8wazqcc7qqvq0axs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-03T20:55:55Z"
  mac: ENC[AES256_GCM,data:gU8Xd5OOzegkxtR7geOkxHh2QdHM7Y7BkMd7gapQkQClTuSNh0GZ0CEsq+awvnWvus/lPCgBLT7LxhyW7SlhTOMvgLStdI07wkALtVYa/AoX28rJwkyzrXnurtpxfwTLUzbt8+hj8ZXxexCw8qYdsqzyvlt2W3g3EjSjF9K7QFw=,iv:Wzsz8mHTR79a5j6tYn6mgIVxzn0XXEcbCawNxAcFOpw=,tag:lP1ZeoYVe6vijMIE28hYTw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
