---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ciliumnetworkpolicy.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml
  - ./identity-secret.sops.yaml
  - ./networkpolicy.yaml
  - ./ocirepository.yaml
  - ./secret.sops.yaml
