apiVersion: v1
kind: Secret
metadata:
  name: actual-budget-secret
stringData:
  ACTUAL_OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:6e4Qwe6fNEmWQ9nBZrybTgdLb6dVVIn5uJlGYzGq1aw=,iv:zJW2ZB34jF6ya30+IDANaeVNnsalr+pa6P3qJrf/KEQ=,tag:xSSExS93VUN10G6zCLjCyg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGdyN0ltQmZn
        VWNPQzIzMjdvTGY1SVhZR202cjdBYlREdThGdEEzSUFjVzZsamd2dUZUKzZUZmdD
        ZFo2NmdicnJHZTVQM3V0ZC9NeXRYSTg0K0lCbnlkN1BrelZLTmdULytrNDlJSHNm
        cWtLYk4zc29WTE1LVnI4eDlGUWpuYndUWGVLOXA5Zmk1enBvZ2F3VythWFh2WXhs
        blRtcEI4cW9ZeFJ6eXU5SVZIWVQxVXBVNHdNa0c3c21BUkxtN3pMV2ZVZkxERE1w
        V0NIKytMWTE4R21OR0JZWXVKVVVaYkE0Z2YvbC9ZNFVkbkhOblozbnVQVTVJSVlo
        L2ZQVXVVcklqZU56RjZLWC9NZkQ5SXhWT2VyaDd5NmxoWFFrdE9lY2UweVA2NFNS
        UmJ2QXRaajBHZGtwSFN2OFBLTkxBdFRmSVYvYlVQNmNRTlM0Z0h3Yk1MMlBYY3Z5
        RjFVUGNkenVudnQ1MVA4bHlkdnJjNlpNaHV6Y2crd2NLaTFEajNGUmpzSTFGWFBG
        V0ovY0ZHUGFQZldZQVdUN2NoZXJGU1Bhd1ZwZktiWFA5ZmRQYXFETEkrM3pWeGNG
        aEFHa1JjejYwbk8raThnd1lhWGxFblYveHVCMkpwWk5FQ3BBc0pUalBUeFVndDlh
        ejU1UWNaM3JBMENqRzhad3Q1Z2FXUmxNYzNuN0t3THc3NWRMY1h0SUd1bTdyVTNO
        ZUhhbWYvd25DdklqQ3pHUENoallrbXpUd1k4ZXhjaVNOWksybHFnY1RHZ0NkQWlj
        L1VVSzlhVEx1U1BnUVU5TVZzSnNqOXB6ZFRmZkMwSUNDNDM2MVJibkF0dHljTE8w
        QmxaejhsbUF0V1JvVlBrS1RPUE53SjR5WUt3a0Z3aGJpSWtSaE1wZ2dRWmRRQ0Jn
        OHN2ZUJ0WUV1eHhQQkdhOHlpRStZUERJM3QycU5VNzhCcHVaZ1lyQ1RuZFNjei93
        eG9PSDV2eloxbjRkaXVFbHdZWVdjK01JRzN4YU10bWpLc1RMRVNnSUN2S0I0TVJE
        QWl2SXluVVRWNkkwR3p1eWwrZ1A3TlJkZUxmR2hGYWJ1MmNORUdSNVFEdGlLckdl
        UEs5WmdabkkrTEhKVjNuem02VUcwRHh0ZVZWS01tajI4WU5VcDV0eWM4aGJCR201
        a3I1QkpSMnkwcGlwT2tlQXNzbXAvRStlczdHWm5aU0RLRkJBQVNUR0xVdElQWDFN
        cms4ekNIUUFRbHJ2ZXFtV0d2MWdwVE9mSjVFaCtqL1JXQ1dyUGs0eWdsY004S3oy
        a2VzajBaMnVKcmwxZ0lqeHZXL0FJWS9nZmQrWWVHL1ovd21SRmkzWXFicjNNTkNM
        QXFiSS9WQ3Bsc25Fb05KR2NQd1gzck5qamNwb2RDb2Q2aENXdkNuYmpJeHBHUEo5
        eEhDVFh3WWwrdE0ybkUvamxiU094TXJBVVJQQnNZaE1yeExGekoraDl0QlREV202
        MDhXRU9kb1ZmVklXMWFTQm5yd2pUZFNaVVJhTG1VaWJWRGltbDF3V0lIc3ZwTFFo
        bHQyRUFpYTN4Zkk2SkJ2Njg4TkhoVk8vREJ3bzBoaFVYc3pWQjE3S3B1THpNdGtj
        bmVKeXliT0pIYWwrZlVXQ251Q1IwMVpZSk96VzdxTElZaFl3SWUzYXlISHZVTm9F
        YjlVLzUvMDNzYXYzVXNDRnJUVU5MZzZwNTRPVEtPY045VGI4ZTNweEdNVXA0ODZM
        RnVqWHA5alo3UTJMZ3lWM0JKcFBDRi95M2F2N0ZVWlIwY2lDSHVhRTdIV05xOFB3
        cXpHT3A0VE1RNXdxTEsxSVYybnZMRGRsZk0rbkc3WER4KzZ0dzZpNVhKM25MbEhQ
        NDkxaVVVaHV5cVVoUjZ3aTlGTllPZlZrcDRINXRoWnhId0xFQjNyZDI1RTY0d09N
        K0cwQjlnajlrd1lpNi9ZVXd2bmVodG1zWTBQSXBZdEZsLytVZFB2ajVWRStQQQoz
        d2VwU2Z4a3F1U3lrNThHVWVEMDZiUDh2VGJqaU1LeU5MNDdFZWJzaHpzCi0tLSBN
        dWJXNVVNTTZtMVNKY0VHRGJPMGtaSWJtVUl3T3FHZlNUbG1hTVlLaWVjClsw+JQR
        WX00rTdvz7COpok35Kv8qT/CGYSJobaF0a9C5MPq7HKzZgdLomKfkYtQ9sfX6q9I
        7jlxqF3R37aNpBA=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1zev40t6r439fzn9dddxrz5zq9vzzmq385rv59s9svf7qred0fqcsp4y2pn4rhpgjjgez862xf4rqyy2ytldkrw2g29fpesmmq7agzterhldmgsz3zjjwla5c7lq2hmac8d33vdg7js53zcrk8wtfzewq50ugrfzw3x0ghlrl0pmuhy3y8xhytgtyhfwqpup2gurfnkd8c2rq4q2w5zcvqg5h9ydcdlv4jhhkgwf2d39njwgc497vfd82fat4c50yedx2ajedtpeyrlqnf0fze8p0za3hypkzaqfnrhfx8zgrfp7qx3gzez6tf5vcpxyrzlup5evf0tqhtz30t4ckt9njc4vrw2mgtvxkl9upn9y34g2r36g4vvdy6mzse2vk5k26gym5cfr4ef65wvkhcv7yqag6mpfkqmxtzxe8yedhsnq2x9vuxqyx47rkvn5g0w6nf8yqs8t2gp5cp0kdxruesp0wh76n5wmm0ztx4pktwrharstredmlqeec22045wm3f9hhkz6fr4y94vzugr9ghaqhswrh7dx6yc9mc0y6u6drgtxesf0jsh89xg3u47yjvd3rnkdu22ls5j0hpcwymlr6gp8pt9qyc6swsczj50rq9rppsl6ufxv2kwcrmvtvn2svj56ryukk006l3wwe9plx6wz24y3xq0jje7rxkc86w59d0y6q2wf49whuzt28xf3zvmp25qwzxn4ms24pkw7g5w6xq5nnwyvanl72kqcztlssyjs9hzdrq2m268mktc8jhydnvezteghq40r0k772szggkhv8k8gvf0rn7346h0cv852cksx53tqdgqsfmjfsv6m6gcdhc4t059hx2gh4ckryzptper3hg3265usmnyclfjdxxr445602vr38xlywucmmxlrjf36nrn060jrtvqrfayc7tt96skkt754fqgj8zwd95cht9wz3x4ptsruceym727xv3fzqz56vt2my6slx2dwdpg962mpuxgdh3mz8wq5y3ymgcwakx9tjcge4ah6883qmhyevkvgay08t54x25yqkdtt2naspeyp97w04jjcv2kcgdzutzy5s23855aahl2q9rvwgc5cke56fg08x9v8mvydmgc48248hxx96ewjlhscl633afyaceeynk4tk2hvsuxd546ukp23s7crsj7rne2rqrxwkvkpld87z86wpcus2xf2h6cjr3xvcfrxqnphm08r3gxyn8g9v4sjztdv3p4qvfdk55sv66lryh5dmtxu99hwuexhpfyfz5496rawwc3rvtep4ylzgvaekhs4eadfzy6vckwpp37hd8q6xyvm2vcja69ppdzj62k22pg8u64l024skq3ejcgr3cqnfv5e5dzryxyr9qtc23t8pn0mhegj9caa89qnd6ck9xpsnfwlckz8xxykqf4egucryapssecetxt4e4q599g4a0y4ccswpykhsrd5wjvt32gtena5kg38yd04d4y3zhdjjlnp3tqwzux090268x3pvgqfyelr04ftnrjrk3hm9hrsg6gzex8qul3fu3uq8wg4aqr8vgeff5as5lcdq6zlkc3p9jpcdgar82wxxwgzevfju9uf8v2kqgjpfy5tsldv9udjsdaj2tf4uuknp0f6yksfznd8mtrmle0kjqa9qjeg7k8u8nll3k3qc0s0c9qxj7atp4janes0ud9ke9jljy3grf2th0my3eqcn4aumntx5276g3ccvy6ueujcvy8npz26x277tc995756rptur0jjwx06qeqpdcdguugnk083js8xf2q7gcsmtympfjvg8xrempvj29qrsaym3dqlkv3gjayelfnpl02acd3nsqv69jqg8ewkjp3spwnvc7ql05ke37utdttcgq0fhc8a4npxj2jhhdhazu494z4n772qq8wazqcc7qqvq0axs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-07T19:38:31Z"
  mac: ENC[AES256_GCM,data:G3ycuhY7yL0RtiVxq+ha+BNaEFdPjGqkmuVzvZGh68hvfhEXvTqmqqxLB5150I08YPHNCNYZIzDhyvASuxHY+lxuhGcGrYLq43ipbdJ5XBlKzJL4Jc3VEczXmpCRa+w/fSGdjIC4DUzKoYvFtWXirK3QW6VbJUCrKaLuSDTD5Xw=,iv:oWcCaCVn6cl9yvdLh5PhsNyjs232Jk0Z8QVNol9i32k=,tag:DsyDI7bJVVUHVWkNHMtFhQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
