apiVersion: v1
kind: Secret
metadata:
  name: pegaprox-metrics
stringData:
  token: ENC[AES256_GCM,data:/YJqWNsiSoF5GIWYUIOQ54e0cwQE8H4N2nRfGrXG9pQNZJPTPrXpYPY7ziZta9N7k3aarg==,iv:RHwOfpWfVuExtk2zUD5Zk/uuMcN7Wcm4Te/jojwySQM=,tag:L57vfakxPi6YAZlf8Aq/XA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEhKb3lMK01p
        cWpmeXVWKzlqRDFqUTFuY0xjRHd3NEhqWkNRbjNhbUovbHJXbFZuWUpUZ1JpbU9x
        RXdGUGJIR3ZHUkRiTVRoYVVocWtvc1dpWUxhWTlhckdJeFA5T1REQk1QZFh1c0ZP
        eDVUbVl5RkhzcVJxcjB4Y0x0NDdjdGQ4Zm5oZEpLeDd5YlV2NWhVWld4RTVDYUFz
        MGpwaFhWTE91L3kvSkdSWGYzVW1ORWFISmdpSlNpRE5taFlPMmRHWmNwV0NqWEln
        d1Y3ZndLblFWTDNHTXdlS1lSQytiRjlzU0IzUmR1aWJXaXhSQklaSzRNTkl5UnR6
        SGphWSsrUVZKd1RKc09oNHBQSmlMYi84RkcrUDJRajlrZCtpWGQvUDZxRlllbzg2
        YTQrek9oODNyS29rM01nczN3aEhySnl1NVhIdndtQXV4WlV3ZlJrV1A0QkhVN2tl
        ZmdocWRjaWJzaHdlVU5yT3NmSDdJNWR5dEVLM1JIUjAzYlZiV0hIbVZuc3RvZG1j
        cVZha09icmtzRDhoYm40elliVWV6QU9QcmxXWmNnOFNkN2pRaDR0S2x5bHhHN3pD
        TFJXcDI3MmRxb05OUnFoTFVoSlpkMThVZjBaZDFFSnlFWnN4MW92N2RjTnVueG5q
        aWVpVVhpbCsyM04rbGE4WlRiZmVCTmVvbVVYV2p0VmFicW4yNWhPY1pmVGswdEp1
        Qzd4Z2dkR3k4UVJMMXllVlgxdEFpZHBGblBKL3JObG82RGlPcG1KejFxOUdkbHBk
        OXR3KzhQUkk3THlqcTlURzJQUkczcmg1L051RExTcm1CS2R2ZjlXZC9HVEpHS1F6
        N0FLZzI4a01KNjhzZVQwZWsyZDhEWHhJL3o1dzl0NU5vL1NPMFFUcWp0V21maEhn
        a1FEaEJiV3FZRWE2MlBZblZld25iS01HeFBtUnJhVTRHSEFtcFYwdU8xekxJSlor
        cGZONVhDaTRnc3NHV3I4VHpLeWhIRjlpcjA2QWFqczF4Zzg4Tkg5TjRwZ2ZqTWpj
        Sy94UE5vUlBLYndKZVRvWE5oL2hCc1dRNkh2b3JybXExT3BNR0w3M1hhZWJrM2J6
        T3RsTWxSUk1aQmo5d1QySHBRcWZieXltajBUQzhGbS9PbHdHa2dkQWNHMDBSZndV
        TFpWeWkwNnF3ZC9rK21PZWYwRTFMM01lM0JaeG9lMFRvNVRyYlZxYWl1UWlPVkdl
        ZmtmZUZCaFAwNU0xV3BzQ09IcFpucnpEci84OFFLemVhbkh6enVOaUM2eDdJcmZK
        RFVEcU0yOWpEd2NtSDdjaVFuNWtWWGdlY0ZoSEFwU2E1VHlzVzJvNnVIVDJwaER2
        cjdqNURUa3p6U1paNmplL3g1TzhhT1NxZXZsNWw3dGRvWjhTa1dCd2lFOUFCd0Jo
        YUNxditZL1JoTDYzbUozZ29TT09adGFYZHV3Smt6cmFqa0hWcnVHU1phblZPRVRl
        T0lVMzk5NW15QW9qLy81M2VFOW9JbWFzWkJ2NVk3Lzk2WFVXQkw0cGptcUFVcExp
        QUYvdU5Xc0tuYWxsNitQSzNnMzErUjFIeUNDNGR6UFJSdUVXT1RJd01jTzFCMzNj
        M2NldUJ0U1I4RnFmK0Q0U1BENHFqcjdCczRIbmxsZ3VoV0twZzRBSU1NZzNaSlNG
        bSt4QnJNVEo1TVRlbjU4S2VRYlZUbndKdnVla1dWb1dQQlFFVms4QUNaUHNpWjlt
        VTY2eUJjOC9tWFN2d29tQ1dRUlNHWmxmUU9xa0R1RzZ5ZFVLREFadTQ1TXJxTmJG
        Z1dKenByUlN2UGZjVStQR2s1YkZURW9ZTlhCZU81cFhGb2cwZ0twNnQzOHJ6WHgz
        d25rWUQ4aTFLZm5PZjdxWkZJd1JXcS9CSURBNEl1QUZhelZOUEptc2R5RDZBcVZj
        WXU4SHVZRFMyQ3hiZGY2MXZYMWx3V293U2ZSR1pOLzBqc0dxZkxJS0lQdEVEZwpB
        WXVQWmdCNlhuM1JhWk5MSGdlbUhYMnd2Vk5OMmNYbStOWVM2L3NaZGk4Ci0tLSBy
        RWdVZHdxTG03Y3ozbWhqaUhSSnFJa2xkQm1DcmUzTk53eW9uc0dxdTdrCoCBNFN5
        urVnNqGgKLHih+He3F0HoS5qK3FqbT7Q5tlClFFIZA3WamaGDXpTqz2VfbFbF/EV
        xmYHz1Wrk1nWgms=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1zev40t6r439fzn9dddxrz5zq9vzzmq385rv59s9svf7qred0fqcsp4y2pn4rhpgjjgez862xf4rqyy2ytldkrw2g29fpesmmq7agzterhldmgsz3zjjwla5c7lq2hmac8d33vdg7js53zcrk8wtfzewq50ugrfzw3x0ghlrl0pmuhy3y8xhytgtyhfwqpup2gurfnkd8c2rq4q2w5zcvqg5h9ydcdlv4jhhkgwf2d39njwgc497vfd82fat4c50yedx2ajedtpeyrlqnf0fze8p0za3hypkzaqfnrhfx8zgrfp7qx3gzez6tf5vcpxyrzlup5evf0tqhtz30t4ckt9njc4vrw2mgtvxkl9upn9y34g2r36g4vvdy6mzse2vk5k26gym5cfr4ef65wvkhcv7yqag6mpfkqmxtzxe8yedhsnq2x9vuxqyx47rkvn5g0w6nf8yqs8t2gp5cp0kdxruesp0wh76n5wmm0ztx4pktwrharstredmlqeec22045wm3f9hhkz6fr4y94vzugr9ghaqhswrh7dx6yc9mc0y6u6drgtxesf0jsh89xg3u47yjvd3rnkdu22ls5j0hpcwymlr6gp8pt9qyc6swsczj50rq9rppsl6ufxv2kwcrmvtvn2svj56ryukk006l3wwe9plx6wz24y3xq0jje7rxkc86w59d0y6q2wf49whuzt28xf3zvmp25qwzxn4ms24pkw7g5w6xq5nnwyvanl72kqcztlssyjs9hzdrq2m268mktc8jhydnvezteghq40r0k772szggkhv8k8gvf0rn7346h0cv852cksx53tqdgqsfmjfsv6m6gcdhc4t059hx2gh4ckryzptper3hg3265usmnyclfjdxxr445602vr38xlywucmmxlrjf36nrn060jrtvqrfayc7tt96skkt754fqgj8zwd95cht9wz3x4ptsruceym727xv3fzqz56vt2my6slx2dwdpg962mpuxgdh3mz8wq5y3ymgcwakx9tjcge4ah6883qmhyevkvgay08t54x25yqkdtt2naspeyp97w04jjcv2kcgdzutzy5s23855aahl2q9rvwgc5cke56fg08x9v8mvydmgc48248hxx96ewjlhscl633afyaceeynk4tk2hvsuxd546ukp23s7crsj7rne2rqrxwkvkpld87z86wpcus2xf2h6cjr3xvcfrxqnphm08r3gxyn8g9v4sjztdv3p4qvfdk55sv66lryh5dmtxu99hwuexhpfyfz5496rawwc3rvtep4ylzgvaekhs4eadfzy6vckwpp37hd8q6xyvm2vcja69ppdzj62k22pg8u64l024skq3ejcgr3cqnfv5e5dzryxyr9qtc23t8pn0mhegj9caa89qnd6ck9xpsnfwlckz8xxykqf4egucryapssecetxt4e4q599g4a0y4ccswpykhsrd5wjvt32gtena5kg38yd04d4y3zhdjjlnp3tqwzux090268x3pvgqfyelr04ftnrjrk3hm9hrsg6gzex8qul3fu3uq8wg4aqr8vgeff5as5lcdq6zlkc3p9jpcdgar82wxxwgzevfju9uf8v2kqgjpfy5tsldv9udjsdaj2tf4uuknp0f6yksfznd8mtrmle0kjqa9qjeg7k8u8nll3k3qc0s0c9qxj7atp4janes0ud9ke9jljy3grf2th0my3eqcn4aumntx5276g3ccvy6ueujcvy8npz26x277tc995756rptur0jjwx06qeqpdcdguugnk083js8xf2q7gcsmtympfjvg8xrempvj29qrsaym3dqlkv3gjayelfnpl02acd3nsqv69jqg8ewkjp3spwnvc7ql05ke37utdttcgq0fhc8a4npxj2jhhdhazu494z4n772qq8wazqcc7qqvq0axs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-06T04:13:51Z"
  mac: ENC[AES256_GCM,data:KKTMQpcg/FN5p+y0dFHLdVEZCLUCFEUw4JoYI5tYZhW7HZwH+4O6GelSN91fGnTftjJPbquZQJw7krdp9lwnK3bzk5yAhhT94MaRAixemaHmeIzuCMILhBPSBUCpG9N3K+IzWHxe8kmuWZq/XCcPRppKNma/TTC5QZWf+WNznDw=,iv:QphU7Il+rKGbH9Z/g8i3SJ+T9QFF19DGrx58mPZbq5Q=,tag:H0aJi8Btc3B9NTZYm7eKEA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
