apiVersion: v1
kind: Secret
metadata:
  name: pocket-id-secret
stringData:
  ENCRYPTION_KEY: ENC[AES256_GCM,data:YqTcJzxiqW1ZnHldC0ytHsEdSjgf0mP7hdD6W9U+ygKKonZR/Owwsy16NVY=,iv:BhEgbNSsYfBW2p5c4cU3HqBumwD7gySTax+vymaLf70=,tag:xGgMNeIF0yuJl5VGrmgwQw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IE1rY1JIWFBh
        NTlVekdWQWdQMXorMDY2QVRKNndEcU5CQXRUY3h2QXNEcXpGcWZ2VmZJcEFoUGtu
        RXFOUmljRWhZTUJLU0dzWHJUVm5Ldmg2M3lHdUFxamtKaTVKRHJGcmpwOVVTbXBs
        Nlhwdk03bDlrajdEWmJGaGZCSk9telRTYnhvVEZCak1Mak40ZTZhSjlkb1I5Ulcv
        b1dPWXVPbTY4OURPUUtuU3MzSGJJZnVub3FOeVZrelMzVURqUU1KelhmNkN3b3ls
        SXZRK0tNaG5tMTV3WnpyYk5JSkxTYjdESVpwRkl2dEZYcE5vWm5WRlJUNk1vWUF3
        K1k2WnhoU0RSNTdxSW41eWxaaHFmTVJJbnZ0OGVYSlpGcjY0elZ2TjBCLzc5aDRZ
        cVlnZEkxY3FmVUZMaVdiY3NQVFZkKzNYeVFUMDdWQy9pbGNtNGtvSjhlTkxhMlBG
        MjBpVjRhYVp1d3htYmEyUm9ST3pIZXNmYlNlV1kxb1pYWlc2cGs5dGdocVBvSmp6
        TE9oOGNuQU10MXBTcTJmTktMMCtlZTlPSFFnT3YrZ1hvZW1MSE91QWFSWnpvY2Jw
        cEdtL3lTSmc2RTI2WHFVNTdrUnp1VC9Tb20vOWRaTGNwdHVrZXRaS1RGSmlzSURn
        WHBGMExySTNsREhFNEJxS1dmZGo4NjEzZ1JnN3R2R1o5UEUxcldPTVE3UmJhZ1d3
        TG1uL21TcDhwYzhhdWR3R2NhU1RRa3huRGk5QWJiTEFEYXpFODd6TkhDaUFCV3la
        ZjNUQm9KY09FSkhUcHNHeHZYRW1ZUUgweVN0K3Y5R1BEYUlJUHdFS3dzeXpEQkJG
        aXhGbXVSclN2MVNLc1BGN2ppWXFOUVlLOHJIS0tnejczeEQ0d0pGcTAzeFFSQU5J
        U2taTXZkTEQvc3lUYTRwbTB4MWgrcTYzTEEycXdxUmVhL3dKeDEwUG5EMEhrbjlN
        cjIxMTN5R3dwNnl2SVQydVBDK2xyaElJZnRTcDBWdE1adkFtQ1BnNXBEMnJyZ2lF
        R05iMk1tNFZ6WTFUK0NJK3BXZ3ljQkRuMEZlQi9sR0xoOUNWOHNkS29TcTlUdFhW
        S3ZMa2Y0elhDbkN1cTRibEtxV0hvMCs3ZlphZEdQRDlTU3RuaXg0S09YOHdNdFlL
        ZUlhaklGQXQ2YWFIMDZmcjR5eXF5NXFyTE05ZDlRR3hlWTIyTnltd3ordTdrdHFU
        MzhLTEF5RlZvOWxOSU81bkp6d3NhMUZpVGxmZjhrc3h6eE5Xa2RPcFpiVENQNGpV
        NFY1OXFiSWFHRWhEazQ1OEd3NlQxM3IvcmppZWV1MkE0QVgxQmwwME0wZXdaNTNC
        dzZOYlc1aFFoOXc5TjNacVV2b0dQN21xbUdVLzlvYlRmZzRBb2FZaDhoMG1nRjY3
        ZUNWeHZYUU1zRU55d1NhbFVEQ2tDRTZDMGp6eExwTDl1K1pqSmFvSU1oR0NKd1Jq
        SVRIMlhGZmVuN1pLVVlRcTlXZWxCT28zZ2FQdHI5ZHEyUlFjQkozYTZKMVF5UnBn
        NVpOekFJRmZrYlhVMkRFdVQ2WkdxZ1N4cnVjSDlKbmplR0t5M3I3MWhxOHJpMjl2
        bGk3UTZ4L25iajYzZzZReUlnNlc4enY0d1FFUEVQRkViUllQSUo2V3VaT3prZTl6
        THZrVXlGanV1b0wwM2NsakRUQXU4YTIyMWxTSURjVERONHNHbWNTd1N0ZDNHTzFx
        MVRRYXd1SGhHMFY5bVRBVEhoUExxbkdSMHdBYVRTeFVqUjZUdUcvTXlDNXlKVVMr
        alUyNHM1Nk02OGRQcCtISzZINkYzVUZrMFAwYmxqenRtTE82QXBta2pnMTZxOUdC
        VTJ5bHNmS0tlS3cxbHdEeWNGc2cvb3dyVlJndGNVSGZxMHc2R1pDWjNTUExKYVha
        NnNmcFA0Y005eVU2VktlMXplSE5ObDlVamxCck9EREVQRHlCOVlBK3djMGxKQQoz
        bmpQelNvazJwS2FqM214M2pMWkxFVDhKWWFGQXRaVVFpYnRRNXhBQVJnCi0tLSB5
        Wi82UnlJL3NDdkxHcXdLbHN0Mm4rRzZkNEo4QTIzamJyYlEwUzREdndjCmKxXoF7
        MLHCrCCeKUnctll5jdOWk6qlhYsSPK/ShUe3l1ke3IaMHJmhAHGjTh2ncnGa+JSz
        CbBRXD5XX/pj6xA=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1zev40t6r439fzn9dddxrz5zq9vzzmq385rv59s9svf7qred0fqcsp4y2pn4rhpgjjgez862xf4rqyy2ytldkrw2g29fpesmmq7agzterhldmgsz3zjjwla5c7lq2hmac8d33vdg7js53zcrk8wtfzewq50ugrfzw3x0ghlrl0pmuhy3y8xhytgtyhfwqpup2gurfnkd8c2rq4q2w5zcvqg5h9ydcdlv4jhhkgwf2d39njwgc497vfd82fat4c50yedx2ajedtpeyrlqnf0fze8p0za3hypkzaqfnrhfx8zgrfp7qx3gzez6tf5vcpxyrzlup5evf0tqhtz30t4ckt9njc4vrw2mgtvxkl9upn9y34g2r36g4vvdy6mzse2vk5k26gym5cfr4ef65wvkhcv7yqag6mpfkqmxtzxe8yedhsnq2x9vuxqyx47rkvn5g0w6nf8yqs8t2gp5cp0kdxruesp0wh76n5wmm0ztx4pktwrharstredmlqeec22045wm3f9hhkz6fr4y94vzugr9ghaqhswrh7dx6yc9mc0y6u6drgtxesf0jsh89xg3u47yjvd3rnkdu22ls5j0hpcwymlr6gp8pt9qyc6swsczj50rq9rppsl6ufxv2kwcrmvtvn2svj56ryukk006l3wwe9plx6wz24y3xq0jje7rxkc86w59d0y6q2wf49whuzt28xf3zvmp25qwzxn4ms24pkw7g5w6xq5nnwyvanl72kqcztlssyjs9hzdrq2m268mktc8jhydnvezteghq40r0k772szggkhv8k8gvf0rn7346h0cv852cksx53tqdgqsfmjfsv6m6gcdhc4t059hx2gh4ckryzptper3hg3265usmnyclfjdxxr445602vr38xlywucmmxlrjf36nrn060jrtvqrfayc7tt96skkt754fqgj8zwd95cht9wz3x4ptsruceym727xv3fzqz56vt2my6slx2dwdpg962mpuxgdh3mz8wq5y3ymgcwakx9tjcge4ah6883qmhyevkvgay08t54x25yqkdtt2naspeyp97w04jjcv2kcgdzutzy5s23855aahl2q9rvwgc5cke56fg08x9v8mvydmgc48248hxx96ewjlhscl633afyaceeynk4tk2hvsuxd546ukp23s7crsj7rne2rqrxwkvkpld87z86wpcus2xf2h6cjr3xvcfrxqnphm08r3gxyn8g9v4sjztdv3p4qvfdk55sv66lryh5dmtxu99hwuexhpfyfz5496rawwc3rvtep4ylzgvaekhs4eadfzy6vckwpp37hd8q6xyvm2vcja69ppdzj62k22pg8u64l024skq3ejcgr3cqnfv5e5dzryxyr9qtc23t8pn0mhegj9caa89qnd6ck9xpsnfwlckz8xxykqf4egucryapssecetxt4e4q599g4a0y4ccswpykhsrd5wjvt32gtena5kg38yd04d4y3zhdjjlnp3tqwzux090268x3pvgqfyelr04ftnrjrk3hm9hrsg6gzex8qul3fu3uq8wg4aqr8vgeff5as5lcdq6zlkc3p9jpcdgar82wxxwgzevfju9uf8v2kqgjpfy5tsldv9udjsdaj2tf4uuknp0f6yksfznd8mtrmle0kjqa9qjeg7k8u8nll3k3qc0s0c9qxj7atp4janes0ud9ke9jljy3grf2th0my3eqcn4aumntx5276g3ccvy6ueujcvy8npz26x277tc995756rptur0jjwx06qeqpdcdguugnk083js8xf2q7gcsmtympfjvg8xrempvj29qrsaym3dqlkv3gjayelfnpl02acd3nsqv69jqg8ewkjp3spwnvc7ql05ke37utdttcgq0fhc8a4npxj2jhhdhazu494z4n772qq8wazqcc7qqvq0axs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-04T16:05:45Z"
  mac: ENC[AES256_GCM,data:sMFOuCTqTHST0fYTFIBXNBwbqvIR1xLJ6zCm6tQBS989Y4lcmcYNV3sah/ejnnlLcUnVPvmIf2P83ENR26IwWQV2Cx2WN8IaQkLP4pwOR9aMK2y8JHAHWDrNfTwcciv4TDblltAndUcTxknSX2p56Nt+MY/Hr85fRDw3W07iJz0=,iv:0NdaSs+1JO29gL7V1+TX74pn9f58uP6zpjYO9Aa+laE=,tag:jbEcw0iCQxuSuwDcplazLA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
